/**
 * Corporate Trade Parties
 * This API manages the data related to corporate trade parties in Santander branches that handle international business. Corporate trade parties represent legal entities that have a particular profile within the bank as, for example, counterparties or customers.  A corporate trade party has a global limit code system (GLCS) party ID that is created in a separate application and registered in the international branches system. When this API uses the GLCS party ID to create a party in a particular international branch, organization identifiers are created for the party and stored in a local database.  The API can be used to: - Create a corporate trade party. - Retrieve a corporate trade party's details. - Update a corporate trade party's details.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.corporatetradeparties.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.corporatetradeparties.rest.dto.Center;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Bank.JSON_PROPERTY_BIC,
  Bank.JSON_PROPERTY_CENTER
})
/**
  * Data structure containing bank details
  */

public class Bank  implements Serializable {
  
  public static final String JSON_PROPERTY_BIC = "bic";
 /**
  * Bank identifier code (BIC)
  */
  
  private String bic;

  public static final String JSON_PROPERTY_CENTER = "center";
  
  private Center center;

  /**
   * Bank identifier code (BIC)
   * @return bic
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_BIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBic() {
    return bic;
  }

  /**
   * Set bic
   */
  @JsonProperty(JSON_PROPERTY_BIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBic(String bic) {
    this.bic = bic;
  }

  public Bank bic(String bic) {
    this.bic = bic;
    return this;
  }

  /**
   * Get center
   * @return center
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CENTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Center getCenter() {
    return center;
  }

  /**
   * Set center
   */
  @JsonProperty(JSON_PROPERTY_CENTER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCenter(Center center) {
    this.center = center;
  }

  public Bank center(Center center) {
    this.center = center;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bank {\n");
    
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("    center: ").append(toIndentedString(center)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

