/**
 * Corporate Trade Parties
 * This API manages the data related to corporate trade parties in Santander branches that handle international business. Corporate trade parties represent legal entities that have a particular profile within the bank as, for example, counterparties or customers.  A corporate trade party has a global limit code system (GLCS) party ID that is created in a separate application and registered in the international branches system. When this API uses the GLCS party ID to create a party in a particular international branch, organization identifiers are created for the party and stored in a local database.  The API can be used to: - Create a corporate trade party. - Retrieve a corporate trade party's details. - Update a corporate trade party's details.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.corporatetradeparties.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Center.JSON_PROPERTY_TYPE,
  Center.JSON_PROPERTY_SHORT_NAME
})
/**
  * Data structure containing information about a bank centre
  */

public class Center  implements Serializable {
  
  public static final String JSON_PROPERTY_TYPE = "type";
 /**
  * Bank centre type
  */
  
  private String type;

  public static final String JSON_PROPERTY_SHORT_NAME = "shortName";
 /**
  * Short name of the bank centre; for example, 'LON' for London, 'FRK' for Frankfurt, and 'MLN' for Milan
  */
  
  private String shortName;

  /**
   * Bank centre type
   * @return type
   **/
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getType() {
    return type;
  }

  /**
   * Set type
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(String type) {
    this.type = type;
  }

  public Center type(String type) {
    this.type = type;
    return this;
  }

  /**
   * Short name of the bank centre; for example, &#39;LON&#39; for London, &#39;FRK&#39; for Frankfurt, and &#39;MLN&#39; for Milan
   * @return shortName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getShortName() {
    return shortName;
  }

  /**
   * Set shortName
   */
  @JsonProperty(JSON_PROPERTY_SHORT_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setShortName(String shortName) {
    this.shortName = shortName;
  }

  public Center shortName(String shortName) {
    this.shortName = shortName;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Center {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    shortName: ").append(toIndentedString(shortName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

