/**
 * Corporate Trade Parties
 * This API manages the data related to corporate trade parties in Santander branches that handle international business. Corporate trade parties represent legal entities that have a particular profile within the bank as, for example, counterparties or customers.  A corporate trade party has a global limit code system (GLCS) party ID that is created in a separate application and registered in the international branches system. When this API uses the GLCS party ID to create a party in a particular international branch, organization identifiers are created for the party and stored in a local database.  The API can be used to: - Create a corporate trade party. - Retrieve a corporate trade party's details. - Update a corporate trade party's details.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.corporatetradeparties.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.corporatetradeparties.rest.dto.Country;
import es.santander.scib.corporatetradeparties.rest.dto.State;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  PostalAddress.JSON_PROPERTY_STREET_NAME,
  PostalAddress.JSON_PROPERTY_STREET_TYPE_CODE,
  PostalAddress.JSON_PROPERTY_STREET_BUILDING_IDENTIFICATION,
  PostalAddress.JSON_PROPERTY_STATE,
  PostalAddress.JSON_PROPERTY_COUNTRY,
  PostalAddress.JSON_PROPERTY_ZIP_CODE,
  PostalAddress.JSON_PROPERTY_FULL_ADDRESS
})
/**
  * Data structure containing information that locates and identifies a postal address
  */

public class PostalAddress  implements Serializable {
  
  public static final String JSON_PROPERTY_STREET_NAME = "streetName";
 /**
  * Name of a street or thoroughfare
  */
  
  private String streetName;

  public static final String JSON_PROPERTY_STREET_TYPE_CODE = "streetTypeCode";
 /**
  * Street type code
  */
  
  private String streetTypeCode;

  public static final String JSON_PROPERTY_STREET_BUILDING_IDENTIFICATION = "streetBuildingIdentification";
 /**
  * Number that identifies the position of a building on a street
  */
  
  private String streetBuildingIdentification;

  public static final String JSON_PROPERTY_STATE = "state";
  
  private State state;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  
  private Country country;

  public static final String JSON_PROPERTY_ZIP_CODE = "zipCode";
 /**
  * Address ZIP code
  */
  
  private String zipCode;

  public static final String JSON_PROPERTY_FULL_ADDRESS = "fullAddress";
 /**
  * Complete address formed by concatenation of the relevant address fields required by each country associated with the bank. The number and order of address fields varies by country.
  */
  
  private String fullAddress;

  /**
   * Name of a street or thoroughfare
   * @return streetName
   **/
  @JsonProperty(JSON_PROPERTY_STREET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStreetName() {
    return streetName;
  }

  /**
   * Set streetName
   */
  @JsonProperty(JSON_PROPERTY_STREET_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public PostalAddress streetName(String streetName) {
    this.streetName = streetName;
    return this;
  }

  /**
   * Street type code
   * @return streetTypeCode
   **/
  @JsonProperty(JSON_PROPERTY_STREET_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStreetTypeCode() {
    return streetTypeCode;
  }

  /**
   * Set streetTypeCode
   */
  @JsonProperty(JSON_PROPERTY_STREET_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreetTypeCode(String streetTypeCode) {
    this.streetTypeCode = streetTypeCode;
  }

  public PostalAddress streetTypeCode(String streetTypeCode) {
    this.streetTypeCode = streetTypeCode;
    return this;
  }

  /**
   * Number that identifies the position of a building on a street
   * @return streetBuildingIdentification
   **/
  @JsonProperty(JSON_PROPERTY_STREET_BUILDING_IDENTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStreetBuildingIdentification() {
    return streetBuildingIdentification;
  }

  /**
   * Set streetBuildingIdentification
   */
  @JsonProperty(JSON_PROPERTY_STREET_BUILDING_IDENTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStreetBuildingIdentification(String streetBuildingIdentification) {
    this.streetBuildingIdentification = streetBuildingIdentification;
  }

  public PostalAddress streetBuildingIdentification(String streetBuildingIdentification) {
    this.streetBuildingIdentification = streetBuildingIdentification;
    return this;
  }

  /**
   * Get state
   * @return state
   **/
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public State getState() {
    return state;
  }

  /**
   * Set state
   */
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setState(State state) {
    this.state = state;
  }

  public PostalAddress state(State state) {
    this.state = state;
    return this;
  }

  /**
   * Get country
   * @return country
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Country getCountry() {
    return country;
  }

  /**
   * Set country
   */
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountry(Country country) {
    this.country = country;
  }

  public PostalAddress country(Country country) {
    this.country = country;
    return this;
  }

  /**
   * Address ZIP code
   * @return zipCode
   **/
  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getZipCode() {
    return zipCode;
  }

  /**
   * Set zipCode
   */
  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public PostalAddress zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

  /**
   * Complete address formed by concatenation of the relevant address fields required by each country associated with the bank. The number and order of address fields varies by country.
   * @return fullAddress
   **/
  @JsonProperty(JSON_PROPERTY_FULL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getFullAddress() {
    return fullAddress;
  }

  /**
   * Set fullAddress
   */
  @JsonProperty(JSON_PROPERTY_FULL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setFullAddress(String fullAddress) {
    this.fullAddress = fullAddress;
  }

  public PostalAddress fullAddress(String fullAddress) {
    this.fullAddress = fullAddress;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostalAddress {\n");
    
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("    streetTypeCode: ").append(toIndentedString(streetTypeCode)).append("\n");
    sb.append("    streetBuildingIdentification: ").append(toIndentedString(streetBuildingIdentification)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    fullAddress: ").append(toIndentedString(fullAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

