/**
 * Corporate Trade Parties
 * This API manages the data related to corporate trade parties in Santander branches that handle international business. Corporate trade parties represent legal entities that have a particular profile within the bank as, for example, counterparties or customers.  A corporate trade party has a global limit code system (GLCS) party ID that is created in a separate application and registered in the international branches system. When this API uses the GLCS party ID to create a party in a particular international branch, organization identifiers are created for the party and stored in a local database.  The API can be used to: - Create a corporate trade party. - Retrieve a corporate trade party's details. - Update a corporate trade party's details.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.corporatetradeparties.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.corporatetradeparties.rest.dto.ElectronicAddress;
import es.santander.scib.corporatetradeparties.rest.dto.PhoneAddress;
import es.santander.scib.corporatetradeparties.rest.dto.WrapperUpdatePartyRequestContactPointPostalAddress;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  WrapperUpdatePartyRequestContactPoint.JSON_PROPERTY_POSTAL_ADDRESS,
  WrapperUpdatePartyRequestContactPoint.JSON_PROPERTY_PHONE_ADDRESS,
  WrapperUpdatePartyRequestContactPoint.JSON_PROPERTY_ELECTRONIC_ADDRESS
})
@JsonTypeName("WrapperUpdatePartyRequest_contactPoint")
/**
  * Data structure containing information about a contact point. A contact point is a phone number, physical address, or virtual address used for communication purposes.
  */

public class WrapperUpdatePartyRequestContactPoint  implements Serializable {
  
  public static final String JSON_PROPERTY_POSTAL_ADDRESS = "postalAddress";
  
  private WrapperUpdatePartyRequestContactPointPostalAddress postalAddress;

  public static final String JSON_PROPERTY_PHONE_ADDRESS = "phoneAddress";
  
  private PhoneAddress phoneAddress;

  public static final String JSON_PROPERTY_ELECTRONIC_ADDRESS = "electronicAddress";
  
  private ElectronicAddress electronicAddress;

  /**
   * Get postalAddress
   * @return postalAddress
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public WrapperUpdatePartyRequestContactPointPostalAddress getPostalAddress() {
    return postalAddress;
  }

  /**
   * Set postalAddress
   */
  @JsonProperty(JSON_PROPERTY_POSTAL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPostalAddress(WrapperUpdatePartyRequestContactPointPostalAddress postalAddress) {
    this.postalAddress = postalAddress;
  }

  public WrapperUpdatePartyRequestContactPoint postalAddress(WrapperUpdatePartyRequestContactPointPostalAddress postalAddress) {
    this.postalAddress = postalAddress;
    return this;
  }

  /**
   * Get phoneAddress
   * @return phoneAddress
   **/
  @JsonProperty(JSON_PROPERTY_PHONE_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PhoneAddress getPhoneAddress() {
    return phoneAddress;
  }

  /**
   * Set phoneAddress
   */
  @JsonProperty(JSON_PROPERTY_PHONE_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPhoneAddress(PhoneAddress phoneAddress) {
    this.phoneAddress = phoneAddress;
  }

  public WrapperUpdatePartyRequestContactPoint phoneAddress(PhoneAddress phoneAddress) {
    this.phoneAddress = phoneAddress;
    return this;
  }

  /**
   * Get electronicAddress
   * @return electronicAddress
   **/
  @JsonProperty(JSON_PROPERTY_ELECTRONIC_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public ElectronicAddress getElectronicAddress() {
    return electronicAddress;
  }

  /**
   * Set electronicAddress
   */
  @JsonProperty(JSON_PROPERTY_ELECTRONIC_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setElectronicAddress(ElectronicAddress electronicAddress) {
    this.electronicAddress = electronicAddress;
  }

  public WrapperUpdatePartyRequestContactPoint electronicAddress(ElectronicAddress electronicAddress) {
    this.electronicAddress = electronicAddress;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrapperUpdatePartyRequestContactPoint {\n");
    
    sb.append("    postalAddress: ").append(toIndentedString(postalAddress)).append("\n");
    sb.append("    phoneAddress: ").append(toIndentedString(phoneAddress)).append("\n");
    sb.append("    electronicAddress: ").append(toIndentedString(electronicAddress)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

