/**
 * Corporate Trade Parties
 * This API manages the data related to corporate trade parties in Santander branches that handle international business. Corporate trade parties represent legal entities that have a particular profile within the bank as, for example, counterparties or customers.  A corporate trade party has a global limit code system (GLCS) party ID that is created in a separate application and registered in the international branches system. When this API uses the GLCS party ID to create a party in a particular international branch, organization identifiers are created for the party and stored in a local database.  The API can be used to: - Create a corporate trade party. - Retrieve a corporate trade party's details. - Update a corporate trade party's details.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.corporatetradeparties.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.corporatetradeparties.rest.dto.Bank;
import es.santander.scib.corporatetradeparties.rest.dto.PartyType;
import es.santander.scib.corporatetradeparties.rest.dto.StatusInfo;
import es.santander.scib.corporatetradeparties.rest.dto.WrapperUpdatePartyRequestContactPoint;
import es.santander.scib.corporatetradeparties.rest.dto.WrapperUpdatePartyRequestOrganization;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  WrapperUpdatePartyRequest.JSON_PROPERTY_ORGANIZATION,
  WrapperUpdatePartyRequest.JSON_PROPERTY_CONTACT_POINT,
  WrapperUpdatePartyRequest.JSON_PROPERTY_TYPE,
  WrapperUpdatePartyRequest.JSON_PROPERTY_STATUS_INFO,
  WrapperUpdatePartyRequest.JSON_PROPERTY_BANK
})
/**
  * Data structure containing information about a party. A party is a person or an organization that is involved in an activity.
  */

public class WrapperUpdatePartyRequest  implements Serializable {
  
  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  
  private WrapperUpdatePartyRequestOrganization organization;

  public static final String JSON_PROPERTY_CONTACT_POINT = "contactPoint";
  
  private WrapperUpdatePartyRequestContactPoint contactPoint;

  public static final String JSON_PROPERTY_TYPE = "type";
  
  private PartyType type;

  public static final String JSON_PROPERTY_STATUS_INFO = "statusInfo";
  
  private StatusInfo statusInfo;

  public static final String JSON_PROPERTY_BANK = "bank";
  
  private Bank bank;

  /**
   * Get organization
   * @return organization
   **/
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WrapperUpdatePartyRequestOrganization getOrganization() {
    return organization;
  }

  /**
   * Set organization
   */
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(WrapperUpdatePartyRequestOrganization organization) {
    this.organization = organization;
  }

  public WrapperUpdatePartyRequest organization(WrapperUpdatePartyRequestOrganization organization) {
    this.organization = organization;
    return this;
  }

  /**
   * Get contactPoint
   * @return contactPoint
   **/
  @JsonProperty(JSON_PROPERTY_CONTACT_POINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public WrapperUpdatePartyRequestContactPoint getContactPoint() {
    return contactPoint;
  }

  /**
   * Set contactPoint
   */
  @JsonProperty(JSON_PROPERTY_CONTACT_POINT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setContactPoint(WrapperUpdatePartyRequestContactPoint contactPoint) {
    this.contactPoint = contactPoint;
  }

  public WrapperUpdatePartyRequest contactPoint(WrapperUpdatePartyRequestContactPoint contactPoint) {
    this.contactPoint = contactPoint;
    return this;
  }

  /**
   * Get type
   * @return type
   **/
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PartyType getType() {
    return type;
  }

  /**
   * Set type
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setType(PartyType type) {
    this.type = type;
  }

  public WrapperUpdatePartyRequest type(PartyType type) {
    this.type = type;
    return this;
  }

  /**
   * Get statusInfo
   * @return statusInfo
   **/
  @JsonProperty(JSON_PROPERTY_STATUS_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusInfo getStatusInfo() {
    return statusInfo;
  }

  /**
   * Set statusInfo
   */
  @JsonProperty(JSON_PROPERTY_STATUS_INFO)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatusInfo(StatusInfo statusInfo) {
    this.statusInfo = statusInfo;
  }

  public WrapperUpdatePartyRequest statusInfo(StatusInfo statusInfo) {
    this.statusInfo = statusInfo;
    return this;
  }

  /**
   * Get bank
   * @return bank
   **/
  @JsonProperty(JSON_PROPERTY_BANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Bank getBank() {
    return bank;
  }

  /**
   * Set bank
   */
  @JsonProperty(JSON_PROPERTY_BANK)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBank(Bank bank) {
    this.bank = bank;
  }

  public WrapperUpdatePartyRequest bank(Bank bank) {
    this.bank = bank;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrapperUpdatePartyRequest {\n");
    
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    contactPoint: ").append(toIndentedString(contactPoint)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    statusInfo: ").append(toIndentedString(statusInfo)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

