/**
 * Corporate Trade Parties
 * This API manages the data related to corporate trade parties in Santander branches that handle international business. Corporate trade parties represent legal entities that have a particular profile within the bank as, for example, counterparties or customers.  A corporate trade party has a global limit code system (GLCS) party ID that is created in a separate application and registered in the international branches system. When this API uses the GLCS party ID to create a party in a particular international branch, organization identifiers are created for the party and stored in a local database.  The API can be used to: - Create a corporate trade party. - Retrieve a corporate trade party's details. - Update a corporate trade party's details.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.corporatetradeparties.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.corporatetradeparties.rest.dto.Country;
import es.santander.scib.corporatetradeparties.rest.dto.EconomicActivity;
import es.santander.scib.corporatetradeparties.rest.dto.IdentificationDocument;
import es.santander.scib.corporatetradeparties.rest.dto.OrganizationName;
import es.santander.scib.corporatetradeparties.rest.dto.PlaceOfRegistration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_ORGANIZATION_ID,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_TYPE_CODE,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_DOCUMENTS,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_ORGANIZATION_NAME,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_COUNTRY_OF_OPERATION,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_ACCOUNTING_SECTOR_CODE,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_PLACE_OF_REGISTRATION,
  WrapperCreatePartyRequestOrganization.JSON_PROPERTY_ECONOMIC_ACTIVITY
})
@JsonTypeName("WrapperCreatePartyRequest_organization")
/**
  * Data structure containing information about a legal entity
  */

public class WrapperCreatePartyRequestOrganization  implements Serializable {
  
  public static final String JSON_PROPERTY_ORGANIZATION_ID = "organizationId";
 /**
  * Unique legal entity ID
  */
  
  private String organizationId;

  public static final String JSON_PROPERTY_TYPE_CODE = "typeCode";
 /**
  * Code for the organization type
  */
  
  private String typeCode;

  public static final String JSON_PROPERTY_DOCUMENTS = "documents";
 /**
  * Array of documents
  */
  
  private List<@Valid IdentificationDocument> documents = null;

  public static final String JSON_PROPERTY_ORGANIZATION_NAME = "organizationName";
  
  private OrganizationName organizationName;

  public static final String JSON_PROPERTY_COUNTRY_OF_OPERATION = "countryOfOperation";
  
  private Country countryOfOperation;

  public static final String JSON_PROPERTY_ACCOUNTING_SECTOR_CODE = "accountingSectorCode";
 /**
  * Accounting sector code
  */
  
  private String accountingSectorCode;

  public static final String JSON_PROPERTY_PLACE_OF_REGISTRATION = "placeOfRegistration";
  
  private PlaceOfRegistration placeOfRegistration;

  public static final String JSON_PROPERTY_ECONOMIC_ACTIVITY = "economicActivity";
  
  private EconomicActivity economicActivity;

  /**
   * Unique legal entity ID
   * @return organizationId
   **/
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getOrganizationId() {
    return organizationId;
  }

  /**
   * Set organizationId
   */
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganizationId(String organizationId) {
    this.organizationId = organizationId;
  }

  public WrapperCreatePartyRequestOrganization organizationId(String organizationId) {
    this.organizationId = organizationId;
    return this;
  }

  /**
   * Code for the organization type
   * @return typeCode
   **/
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTypeCode() {
    return typeCode;
  }

  /**
   * Set typeCode
   */
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public WrapperCreatePartyRequestOrganization typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

  /**
   * Array of documents
   * @return documents
   **/
  @JsonProperty(JSON_PROPERTY_DOCUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid IdentificationDocument> getDocuments() {
    return documents;
  }

  /**
   * Set documents
   */
  @JsonProperty(JSON_PROPERTY_DOCUMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocuments(List<@Valid IdentificationDocument> documents) {
    this.documents = documents;
  }

  public WrapperCreatePartyRequestOrganization documents(List<@Valid IdentificationDocument> documents) {
    this.documents = documents;
    return this;
  }

  public WrapperCreatePartyRequestOrganization addDocumentsItem(IdentificationDocument documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * Get organizationName
   * @return organizationName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OrganizationName getOrganizationName() {
    return organizationName;
  }

  /**
   * Set organizationName
   */
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationName(OrganizationName organizationName) {
    this.organizationName = organizationName;
  }

  public WrapperCreatePartyRequestOrganization organizationName(OrganizationName organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * Get countryOfOperation
   * @return countryOfOperation
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_COUNTRY_OF_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Country getCountryOfOperation() {
    return countryOfOperation;
  }

  /**
   * Set countryOfOperation
   */
  @JsonProperty(JSON_PROPERTY_COUNTRY_OF_OPERATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountryOfOperation(Country countryOfOperation) {
    this.countryOfOperation = countryOfOperation;
  }

  public WrapperCreatePartyRequestOrganization countryOfOperation(Country countryOfOperation) {
    this.countryOfOperation = countryOfOperation;
    return this;
  }

  /**
   * Accounting sector code
   * @return accountingSectorCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ACCOUNTING_SECTOR_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountingSectorCode() {
    return accountingSectorCode;
  }

  /**
   * Set accountingSectorCode
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNTING_SECTOR_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountingSectorCode(String accountingSectorCode) {
    this.accountingSectorCode = accountingSectorCode;
  }

  public WrapperCreatePartyRequestOrganization accountingSectorCode(String accountingSectorCode) {
    this.accountingSectorCode = accountingSectorCode;
    return this;
  }

  /**
   * Get placeOfRegistration
   * @return placeOfRegistration
   **/
  @JsonProperty(JSON_PROPERTY_PLACE_OF_REGISTRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PlaceOfRegistration getPlaceOfRegistration() {
    return placeOfRegistration;
  }

  /**
   * Set placeOfRegistration
   */
  @JsonProperty(JSON_PROPERTY_PLACE_OF_REGISTRATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPlaceOfRegistration(PlaceOfRegistration placeOfRegistration) {
    this.placeOfRegistration = placeOfRegistration;
  }

  public WrapperCreatePartyRequestOrganization placeOfRegistration(PlaceOfRegistration placeOfRegistration) {
    this.placeOfRegistration = placeOfRegistration;
    return this;
  }

  /**
   * Get economicActivity
   * @return economicActivity
   **/
  @JsonProperty(JSON_PROPERTY_ECONOMIC_ACTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public EconomicActivity getEconomicActivity() {
    return economicActivity;
  }

  /**
   * Set economicActivity
   */
  @JsonProperty(JSON_PROPERTY_ECONOMIC_ACTIVITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEconomicActivity(EconomicActivity economicActivity) {
    this.economicActivity = economicActivity;
  }

  public WrapperCreatePartyRequestOrganization economicActivity(EconomicActivity economicActivity) {
    this.economicActivity = economicActivity;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class WrapperCreatePartyRequestOrganization {\n");
    
    sb.append("    organizationId: ").append(toIndentedString(organizationId)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    countryOfOperation: ").append(toIndentedString(countryOfOperation)).append("\n");
    sb.append("    accountingSectorCode: ").append(toIndentedString(accountingSectorCode)).append("\n");
    sb.append("    placeOfRegistration: ").append(toIndentedString(placeOfRegistration)).append("\n");
    sb.append("    economicActivity: ").append(toIndentedString(economicActivity)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

