/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.client;

import es.santander.scib.gboentities.rest.dto.Entity;
import jakarta.ws.rs.*;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * GBO Entities
 *
 * <p>
 * It allows the possibility of standardizing the way entities are created and
 * generated for the different regions and global entities of GBO (Global
 * Backoffice), allowing the creation of entities in a single way for the
 * different users with a new way that allows this action to be carried out.
 *
 */

@RegisterRestClient(configKey = "scib-api-gateway")
@RegisterProvider(ApiExceptionMapper.class)
@Path("/entities")
public interface EntitiesApi {

    /**
     * Creates an operational entity.
     *
     * Creates an operational entity.
     *
     */
    @POST

    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Entity createEntities(@HeaderParam("authorization") @NotNull String authorization,
            @HeaderParam("x-santander-client-id") @NotNull String xSantanderClientId, @Valid Entity entity,
            @HeaderParam("x-santander-device") String xSantanderDevice,
            @HeaderParam("accept-language") String acceptLanguage, @HeaderParam("if-none-match") String ifNoneMatch,
            @HeaderParam("if-match") String ifMatch, @HeaderParam("x-b3-traceid") String xB3Traceid,
            @HeaderParam("x-b3-parentspanid") String xB3Parentspanid, @HeaderParam("x-b3-spanid") String xB3Spanid,
            @HeaderParam("x-b3-sampled") String xB3Sampled) throws ApiException, ProcessingException;

    /**
     * Retrieves operational entities.
     *
     * Retrieves operational entities filtering by GLCS (Global Limit Code System).
     *
     */
    @GET

    @Produces({ "application/json" })
    Entity retrieveEntities(@HeaderParam("authorization") @NotNull String authorization,
            @HeaderParam("x-santander-client-id") @NotNull String xSantanderClientId,
            @HeaderParam("x-santander-device") String xSantanderDevice,
            @HeaderParam("accept-language") String acceptLanguage, @HeaderParam("if-none-match") String ifNoneMatch,
            @HeaderParam("if-match") String ifMatch, @HeaderParam("x-b3-traceid") String xB3Traceid,
            @HeaderParam("x-b3-parentspanid") String xB3Parentspanid, @HeaderParam("x-b3-spanid") String xB3Spanid,
            @HeaderParam("x-b3-sampled") String xB3Sampled, @QueryParam("glcs") @Size(max = 6) String glcs,
            @QueryParam("mei") @Size(max = 10) String mei, @QueryParam("lei") @Size(max = 20) String lei)
            throws ApiException, ProcessingException;

    /**
     * Updates an operational entity.
     *
     * Updates an operational entity.
     *
     */
    @PATCH
    @Path("/{entity_id}")
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    Entity updateEntities(@PathParam("entity_id") String entityId,
            @HeaderParam("authorization") @NotNull String authorization,
            @HeaderParam("x-santander-client-id") @NotNull String xSantanderClientId, @Valid Entity entity,
            @HeaderParam("x-santander-device") String xSantanderDevice,
            @HeaderParam("accept-language") String acceptLanguage, @HeaderParam("if-none-match") String ifNoneMatch,
            @HeaderParam("if-match") String ifMatch, @HeaderParam("x-b3-traceid") String xB3Traceid,
            @HeaderParam("x-b3-parentspanid") String xB3Parentspanid, @HeaderParam("x-b3-spanid") String xB3Spanid,
            @HeaderParam("x-b3-sampled") String xB3Sampled) throws ApiException, ProcessingException;
}
