/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.client;

import es.santander.scib.gboentities.rest.dto.Health;

import jakarta.ws.rs.*;
import jakarta.validation.constraints.*;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * GBO Entities
 *
 * <p>It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 */

@RegisterRestClient(configKey="scib-api-gateway")
@RegisterProvider(ApiExceptionMapper.class)
@Path("/health")
public interface LivenessReadinessApi  {

    /**
     * Retrieve the liveness and the readiness of the service.
     *
     * Retrieve the liveness and the readiness of the service.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    Health retrieveHealth(@HeaderParam("authorization")  @NotNull String authorization, @HeaderParam("x-santander-client-id")  @NotNull String xSantanderClientId, @HeaderParam("x-santander-device")  String xSantanderDevice, @HeaderParam("accept-language")  String acceptLanguage, @HeaderParam("if-none-match")  String ifNoneMatch, @HeaderParam("if-match")  String ifMatch, @HeaderParam("x-b3-traceid")  String xB3Traceid, @HeaderParam("x-b3-parentspanid")  String xB3Parentspanid, @HeaderParam("x-b3-spanid")  String xB3Spanid, @HeaderParam("x-b3-sampled")  String xB3Sampled) throws ApiException, ProcessingException;
}
