/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  AccountIdentification.JSON_PROPERTY_INTERNATIONAL_IDENTIFICATION,
  AccountIdentification.JSON_PROPERTY_ROUTING_NUMBER,
  AccountIdentification.JSON_PROPERTY_ACCOUNT_NUMBER
})
/**
  * Data structure containing information related to account identification
  */

public class AccountIdentification  implements Serializable {
  
  public static final String JSON_PROPERTY_INTERNATIONAL_IDENTIFICATION = "internationalIdentification";
 /**
  * International Bank Account Number (IBAN)
  */
  
  private String internationalIdentification;

  public static final String JSON_PROPERTY_ROUTING_NUMBER = "routingNumber";
 /**
  * Routing number
  */
  
  private String routingNumber;

  public static final String JSON_PROPERTY_ACCOUNT_NUMBER = "accountNumber";
 /**
  * Account number
  */
  
  private String accountNumber;

  /**
   * International Bank Account Number (IBAN)
   * @return internationalIdentification
   **/
  @JsonProperty(JSON_PROPERTY_INTERNATIONAL_IDENTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getInternationalIdentification() {
    return internationalIdentification;
  }

  /**
   * Set internationalIdentification
   */
  @JsonProperty(JSON_PROPERTY_INTERNATIONAL_IDENTIFICATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setInternationalIdentification(String internationalIdentification) {
    this.internationalIdentification = internationalIdentification;
  }

  public AccountIdentification internationalIdentification(String internationalIdentification) {
    this.internationalIdentification = internationalIdentification;
    return this;
  }

  /**
   * Routing number
   * @return routingNumber
   **/
 @Size(min=9,max=24)  @JsonProperty(JSON_PROPERTY_ROUTING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getRoutingNumber() {
    return routingNumber;
  }

  /**
   * Set routingNumber
   */
  @JsonProperty(JSON_PROPERTY_ROUTING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRoutingNumber(String routingNumber) {
    this.routingNumber = routingNumber;
  }

  public AccountIdentification routingNumber(String routingNumber) {
    this.routingNumber = routingNumber;
    return this;
  }

  /**
   * Account number
   * @return accountNumber
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getAccountNumber() {
    return accountNumber;
  }

  /**
   * Set accountNumber
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAccountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
  }

  public AccountIdentification accountNumber(String accountNumber) {
    this.accountNumber = accountNumber;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountIdentification {\n");
    
    sb.append("    internationalIdentification: ").append(toIndentedString(internationalIdentification)).append("\n");
    sb.append("    routingNumber: ").append(toIndentedString(routingNumber)).append("\n");
    sb.append("    accountNumber: ").append(toIndentedString(accountNumber)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

