/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Bank.JSON_PROPERTY_BANK_NAME,
  Bank.JSON_PROPERTY_BIC
})
/**
  * Data structure containing bank details
  */

public class Bank  implements Serializable {
  
  public static final String JSON_PROPERTY_BANK_NAME = "bankName";
 /**
  * Bank name
  */
  
  private String bankName;

  public static final String JSON_PROPERTY_BIC = "bic";
 /**
  * Bank identifier code (BIC)
  */
  
  private String bic;

  /**
   * Bank name
   * @return bankName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_BANK_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBankName() {
    return bankName;
  }

  /**
   * Set bankName
   */
  @JsonProperty(JSON_PROPERTY_BANK_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBankName(String bankName) {
    this.bankName = bankName;
  }

  public Bank bankName(String bankName) {
    this.bankName = bankName;
    return this;
  }

  /**
   * Bank identifier code (BIC)
   * @return bic
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_BIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getBic() {
    return bic;
  }

  /**
   * Set bic
   */
  @JsonProperty(JSON_PROPERTY_BIC)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBic(String bic) {
    this.bic = bic;
  }

  public Bank bic(String bic) {
    this.bic = bic;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Bank {\n");
    
    sb.append("    bankName: ").append(toIndentedString(bankName)).append("\n");
    sb.append("    bic: ").append(toIndentedString(bic)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

