/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.loanservicingcustomers.rest.dto.Identifier;
import es.santander.scib.loanservicingcustomers.rest.dto.Organization;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Customer.JSON_PROPERTY_CUSTOMER_ID,
  Customer.JSON_PROPERTY_PROFILE,
  Customer.JSON_PROPERTY_IDENTIFIERS,
  Customer.JSON_PROPERTY_ORGANIZATION
})
/**
  * Data structure containing information about a customer
  */

public class Customer  implements Serializable {
  
  public static final String JSON_PROPERTY_CUSTOMER_ID = "customerId";
 /**
  * Customer ID. This ID is the risk identifier of the entity, and it is called global limit code system (GLCS) at Santander.
  */
  
  private String customerId;

  public static final String JSON_PROPERTY_PROFILE = "profile";
 /**
  * Profile type for the customer; for example, an investor (lender), a borrower, or a guarantor
  */
  
  private String profile;

  public static final String JSON_PROPERTY_IDENTIFIERS = "identifiers";
 /**
  * Array of identifiers
  */
  
  private List<@Valid Identifier> identifiers = new ArrayList<>();

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  
  private Organization organization;

  /**
   * Customer ID. This ID is the risk identifier of the entity, and it is called global limit code system (GLCS) at Santander.
   * @return customerId
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getCustomerId() {
    return customerId;
  }

  /**
   * Set customerId
   */
  @JsonProperty(JSON_PROPERTY_CUSTOMER_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCustomerId(String customerId) {
    this.customerId = customerId;
  }

  public Customer customerId(String customerId) {
    this.customerId = customerId;
    return this;
  }

  /**
   * Profile type for the customer; for example, an investor (lender), a borrower, or a guarantor
   * @return profile
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getProfile() {
    return profile;
  }

  /**
   * Set profile
   */
  @JsonProperty(JSON_PROPERTY_PROFILE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setProfile(String profile) {
    this.profile = profile;
  }

  public Customer profile(String profile) {
    this.profile = profile;
    return this;
  }

  /**
   * Array of identifiers
   * @return identifiers
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid Identifier> getIdentifiers() {
    return identifiers;
  }

  /**
   * Set identifiers
   */
  @JsonProperty(JSON_PROPERTY_IDENTIFIERS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIdentifiers(List<@Valid Identifier> identifiers) {
    this.identifiers = identifiers;
  }

  public Customer identifiers(List<@Valid Identifier> identifiers) {
    this.identifiers = identifiers;
    return this;
  }

  public Customer addIdentifiersItem(Identifier identifiersItem) {
    if (this.identifiers == null) {
      this.identifiers = new ArrayList<>();
    }
    this.identifiers.add(identifiersItem);
    return this;
  }

  /**
   * Get organization
   * @return organization
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Organization getOrganization() {
    return organization;
  }

  /**
   * Set organization
   */
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganization(Organization organization) {
    this.organization = organization;
  }

  public Customer organization(Organization organization) {
    this.organization = organization;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Customer {\n");
    
    sb.append("    customerId: ").append(toIndentedString(customerId)).append("\n");
    sb.append("    profile: ").append(toIndentedString(profile)).append("\n");
    sb.append("    identifiers: ").append(toIndentedString(identifiers)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

