/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  ElectronicAddress.JSON_PROPERTY_EMAIL_ADDRESS,
  ElectronicAddress.JSON_PROPERTY_DISPLAY_NAME
})
/**
  * Data structure containing information that identifies an electronic address
  */

public class ElectronicAddress  implements Serializable {
  
  public static final String JSON_PROPERTY_EMAIL_ADDRESS = "emailAddress";
 /**
  * Email address
  */
  
  private String emailAddress;

  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
 /**
  * Display name for the person or organization
  */
  
  private String displayName;

  /**
   * Email address
   * @return emailAddress
   **/
  @NotNull
 @Size(min=2,max=256)  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getEmailAddress() {
    return emailAddress;
  }

  /**
   * Set emailAddress
   */
  @JsonProperty(JSON_PROPERTY_EMAIL_ADDRESS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEmailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
  }

  public ElectronicAddress emailAddress(String emailAddress) {
    this.emailAddress = emailAddress;
    return this;
  }

  /**
   * Display name for the person or organization
   * @return displayName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDisplayName() {
    return displayName;
  }

  /**
   * Set displayName
   */
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public ElectronicAddress displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ElectronicAddress {\n");
    
    sb.append("    emailAddress: ").append(toIndentedString(emailAddress)).append("\n");
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

