/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.loanservicingcustomers.rest.dto.OrganizationHierarchy;
import es.santander.scib.loanservicingcustomers.rest.dto.OrganizationName;
import es.santander.scib.loanservicingcustomers.rest.dto.OrganizationTouchpointsInner;
import es.santander.scib.loanservicingcustomers.rest.dto.PlaceOfRegistration;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Organization.JSON_PROPERTY_TYPE_CODE,
  Organization.JSON_PROPERTY_ORGANIZATION_NAME,
  Organization.JSON_PROPERTY_PLACE_OF_REGISTRATION,
  Organization.JSON_PROPERTY_STANDARD_INDUSTRIAL_CLASSIFICATION_CODE,
  Organization.JSON_PROPERTY_HIERARCHY,
  Organization.JSON_PROPERTY_TOUCHPOINTS,
  Organization.JSON_PROPERTY_IS_ACTIVE
})
/**
  * Data structure containing information about a legal entity
  */

public class Organization  implements Serializable {
  
  public static final String JSON_PROPERTY_TYPE_CODE = "typeCode";
 /**
  * Code for the organization type, defining the entity's typology. The value can be, for example, a combination of the following parts: - CDO = Collateralized debt obligation - CLO = Collateralized loan obligation - SPV = Special purpose vehicle
  */
  
  private String typeCode;

  public static final String JSON_PROPERTY_ORGANIZATION_NAME = "organizationName";
  
  private OrganizationName organizationName;

  public static final String JSON_PROPERTY_PLACE_OF_REGISTRATION = "placeOfRegistration";
  
  private PlaceOfRegistration placeOfRegistration;

  public static final String JSON_PROPERTY_STANDARD_INDUSTRIAL_CLASSIFICATION_CODE = "standardIndustrialClassificationCode";
 /**
  * Standard Industrial Classification (SIC) code associated with the organization's business type
  */
  
  private Integer standardIndustrialClassificationCode;

  public static final String JSON_PROPERTY_HIERARCHY = "hierarchy";
  
  private OrganizationHierarchy hierarchy;

  public static final String JSON_PROPERTY_TOUCHPOINTS = "touchpoints";
 /**
  * Array of the organization's touchpoints
  */
  
  private List<@Valid OrganizationTouchpointsInner> touchpoints = new ArrayList<>();

  public static final String JSON_PROPERTY_IS_ACTIVE = "isActive";
 /**
  * Whether the legal entity is active. If so, it is ready to use.
  */
  
  private Boolean isActive;

  /**
   * Code for the organization type, defining the entity&#39;s typology. The value can be, for example, a combination of the following parts: - CDO &#x3D; Collateralized debt obligation - CLO &#x3D; Collateralized loan obligation - SPV &#x3D; Special purpose vehicle
   * @return typeCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getTypeCode() {
    return typeCode;
  }

  /**
   * Set typeCode
   */
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public Organization typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

  /**
   * Get organizationName
   * @return organizationName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OrganizationName getOrganizationName() {
    return organizationName;
  }

  /**
   * Set organizationName
   */
  @JsonProperty(JSON_PROPERTY_ORGANIZATION_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOrganizationName(OrganizationName organizationName) {
    this.organizationName = organizationName;
  }

  public Organization organizationName(OrganizationName organizationName) {
    this.organizationName = organizationName;
    return this;
  }

  /**
   * Get placeOfRegistration
   * @return placeOfRegistration
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_PLACE_OF_REGISTRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PlaceOfRegistration getPlaceOfRegistration() {
    return placeOfRegistration;
  }

  /**
   * Set placeOfRegistration
   */
  @JsonProperty(JSON_PROPERTY_PLACE_OF_REGISTRATION)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPlaceOfRegistration(PlaceOfRegistration placeOfRegistration) {
    this.placeOfRegistration = placeOfRegistration;
  }

  public Organization placeOfRegistration(PlaceOfRegistration placeOfRegistration) {
    this.placeOfRegistration = placeOfRegistration;
    return this;
  }

  /**
   * Standard Industrial Classification (SIC) code associated with the organization&#39;s business type
   * @return standardIndustrialClassificationCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_STANDARD_INDUSTRIAL_CLASSIFICATION_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Integer getStandardIndustrialClassificationCode() {
    return standardIndustrialClassificationCode;
  }

  /**
   * Set standardIndustrialClassificationCode
   */
  @JsonProperty(JSON_PROPERTY_STANDARD_INDUSTRIAL_CLASSIFICATION_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStandardIndustrialClassificationCode(Integer standardIndustrialClassificationCode) {
    this.standardIndustrialClassificationCode = standardIndustrialClassificationCode;
  }

  public Organization standardIndustrialClassificationCode(Integer standardIndustrialClassificationCode) {
    this.standardIndustrialClassificationCode = standardIndustrialClassificationCode;
    return this;
  }

  /**
   * Get hierarchy
   * @return hierarchy
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_HIERARCHY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OrganizationHierarchy getHierarchy() {
    return hierarchy;
  }

  /**
   * Set hierarchy
   */
  @JsonProperty(JSON_PROPERTY_HIERARCHY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setHierarchy(OrganizationHierarchy hierarchy) {
    this.hierarchy = hierarchy;
  }

  public Organization hierarchy(OrganizationHierarchy hierarchy) {
    this.hierarchy = hierarchy;
    return this;
  }

  /**
   * Array of the organization&#39;s touchpoints
   * @return touchpoints
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_TOUCHPOINTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid OrganizationTouchpointsInner> getTouchpoints() {
    return touchpoints;
  }

  /**
   * Set touchpoints
   */
  @JsonProperty(JSON_PROPERTY_TOUCHPOINTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTouchpoints(List<@Valid OrganizationTouchpointsInner> touchpoints) {
    this.touchpoints = touchpoints;
  }

  public Organization touchpoints(List<@Valid OrganizationTouchpointsInner> touchpoints) {
    this.touchpoints = touchpoints;
    return this;
  }

  public Organization addTouchpointsItem(OrganizationTouchpointsInner touchpointsItem) {
    if (this.touchpoints == null) {
      this.touchpoints = new ArrayList<>();
    }
    this.touchpoints.add(touchpointsItem);
    return this;
  }

  /**
   * Whether the legal entity is active. If so, it is ready to use.
   * @return isActive
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsActive() {
    return isActive;
  }

  /**
   * Set isActive
   */
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public Organization isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Organization {\n");
    
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    organizationName: ").append(toIndentedString(organizationName)).append("\n");
    sb.append("    placeOfRegistration: ").append(toIndentedString(placeOfRegistration)).append("\n");
    sb.append("    standardIndustrialClassificationCode: ").append(toIndentedString(standardIndustrialClassificationCode)).append("\n");
    sb.append("    hierarchy: ").append(toIndentedString(hierarchy)).append("\n");
    sb.append("    touchpoints: ").append(toIndentedString(touchpoints)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

