/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.loanservicingcustomers.rest.dto.Bank;
import es.santander.scib.loanservicingcustomers.rest.dto.PartyOrganization;
import es.santander.scib.loanservicingcustomers.rest.dto.PartyType;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Party.JSON_PROPERTY_TYPE,
  Party.JSON_PROPERTY_BANK,
  Party.JSON_PROPERTY_ORGANIZATION
})
/**
  * Data structure containing information about a party. A party is a person or an organization that is involved in an activity.
  */

public class Party  implements Serializable {
  
  public static final String JSON_PROPERTY_TYPE = "type";
  
  private PartyType type;

  public static final String JSON_PROPERTY_BANK = "bank";
  
  private Bank bank;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  
  private PartyOrganization organization;

  /**
   * Get type
   * @return type
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PartyType getType() {
    return type;
  }

  /**
   * Set type
   */
  @JsonProperty(JSON_PROPERTY_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(PartyType type) {
    this.type = type;
  }

  public Party type(PartyType type) {
    this.type = type;
    return this;
  }

  /**
   * Get bank
   * @return bank
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_BANK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Bank getBank() {
    return bank;
  }

  /**
   * Set bank
   */
  @JsonProperty(JSON_PROPERTY_BANK)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBank(Bank bank) {
    this.bank = bank;
  }

  public Party bank(Bank bank) {
    this.bank = bank;
    return this;
  }

  /**
   * Get organization
   * @return organization
   **/
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public PartyOrganization getOrganization() {
    return organization;
  }

  /**
   * Set organization
   */
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(PartyOrganization organization) {
    this.organization = organization;
  }

  public Party organization(PartyOrganization organization) {
    this.organization = organization;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Party {\n");
    
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    bank: ").append(toIndentedString(bank)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

