/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.loanservicingcustomers.rest.dto.Account;
import es.santander.scib.loanservicingcustomers.rest.dto.Party;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StandardSettlementInstructionsSettlementPartiesInner.JSON_PROPERTY_PARTY,
  StandardSettlementInstructionsSettlementPartiesInner.JSON_PROPERTY_ACCOUNT
})
@JsonTypeName("StandardSettlementInstructions_settlementParties_inner")
/**
  * Data structure containing information about a counterparty
  */

public class StandardSettlementInstructionsSettlementPartiesInner  implements Serializable {
  
  public static final String JSON_PROPERTY_PARTY = "party";
  
  private Party party;

  public static final String JSON_PROPERTY_ACCOUNT = "account";
  
  private Account account;

  /**
   * Get party
   * @return party
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_PARTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Party getParty() {
    return party;
  }

  /**
   * Set party
   */
  @JsonProperty(JSON_PROPERTY_PARTY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setParty(Party party) {
    this.party = party;
  }

  public StandardSettlementInstructionsSettlementPartiesInner party(Party party) {
    this.party = party;
    return this;
  }

  /**
   * Get account
   * @return account
   **/
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Account getAccount() {
    return account;
  }

  /**
   * Set account
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccount(Account account) {
    this.account = account;
  }

  public StandardSettlementInstructionsSettlementPartiesInner account(Account account) {
    this.account = account;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardSettlementInstructionsSettlementPartiesInner {\n");
    
    sb.append("    party: ").append(toIndentedString(party)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

