/**
 * Corporate Loan Servicing Customers
 * This API manages customer records in the LoanIQ loan servicing application.  The API can be used to: - Create a customer record. - Create standard settlement instructions for a customer.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: scibapigovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.loanservicingcustomers.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.loanservicingcustomers.rest.dto.Currency;
import es.santander.scib.loanservicingcustomers.rest.dto.StandardSettlementInstructionsSettlementPartiesInner;
import es.santander.scib.loanservicingcustomers.rest.dto.StandardSettlementInstructionsSpecialInstructions;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StandardSettlementInstructions.JSON_PROPERTY_CURRENCY,
  StandardSettlementInstructions.JSON_PROPERTY_SETTLEMENT_PARTIES,
  StandardSettlementInstructions.JSON_PROPERTY_SPECIAL_INSTRUCTIONS
})
/**
  * Data structure containing information about standard settlement instructions. The instructions are used for cash or securities.
  */

public class StandardSettlementInstructions  implements Serializable {
  
  public static final String JSON_PROPERTY_CURRENCY = "currency";
  
  private Currency currency;

  public static final String JSON_PROPERTY_SETTLEMENT_PARTIES = "settlementParties";
 /**
  * Array of parties related to the instruction settlement
  */
  
  private List<@Valid StandardSettlementInstructionsSettlementPartiesInner> settlementParties = new ArrayList<>();

  public static final String JSON_PROPERTY_SPECIAL_INSTRUCTIONS = "specialInstructions";
  
  private StandardSettlementInstructionsSpecialInstructions specialInstructions;

  /**
   * Get currency
   * @return currency
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Currency getCurrency() {
    return currency;
  }

  /**
   * Set currency
   */
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(Currency currency) {
    this.currency = currency;
  }

  public StandardSettlementInstructions currency(Currency currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Array of parties related to the instruction settlement
   * @return settlementParties
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_PARTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid StandardSettlementInstructionsSettlementPartiesInner> getSettlementParties() {
    return settlementParties;
  }

  /**
   * Set settlementParties
   */
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_PARTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSettlementParties(List<@Valid StandardSettlementInstructionsSettlementPartiesInner> settlementParties) {
    this.settlementParties = settlementParties;
  }

  public StandardSettlementInstructions settlementParties(List<@Valid StandardSettlementInstructionsSettlementPartiesInner> settlementParties) {
    this.settlementParties = settlementParties;
    return this;
  }

  public StandardSettlementInstructions addSettlementPartiesItem(StandardSettlementInstructionsSettlementPartiesInner settlementPartiesItem) {
    if (this.settlementParties == null) {
      this.settlementParties = new ArrayList<>();
    }
    this.settlementParties.add(settlementPartiesItem);
    return this;
  }

  /**
   * Get specialInstructions
   * @return specialInstructions
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_SPECIAL_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StandardSettlementInstructionsSpecialInstructions getSpecialInstructions() {
    return specialInstructions;
  }

  /**
   * Set specialInstructions
   */
  @JsonProperty(JSON_PROPERTY_SPECIAL_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSpecialInstructions(StandardSettlementInstructionsSpecialInstructions specialInstructions) {
    this.specialInstructions = specialInstructions;
  }

  public StandardSettlementInstructions specialInstructions(StandardSettlementInstructionsSpecialInstructions specialInstructions) {
    this.specialInstructions = specialInstructions;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardSettlementInstructions {\n");
    
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    settlementParties: ").append(toIndentedString(settlementParties)).append("\n");
    sb.append("    specialInstructions: ").append(toIndentedString(specialInstructions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

