/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO, allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.2.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  EntityResponse.JSON_PROPERTY_ID,
  EntityResponse.JSON_PROPERTY_GLCS
})
/**
  * Data structure containing information about the Entity registration response from SIGOM.
  */

public class EntityResponse  implements Serializable {
  
  public static final String JSON_PROPERTY_ID = "id";
 /**
  * Unique identifier of the operational entity.
  */
  
  private BigDecimal id;

  public static final String JSON_PROPERTY_GLCS = "glcs";
 /**
  * GLCS (Global Limit Code System). Internal and global unique reference of the Legal Entity.
  */
  
  private String glcs;

  public EntityResponse() {
  }

 @JsonCreator
  public EntityResponse(
    @JsonProperty(value = JSON_PROPERTY_ID, required = true) BigDecimal id, 
    @JsonProperty(value = JSON_PROPERTY_GLCS, required = true) String glcs
  ) {
    this.id = id;
    this.glcs = glcs;
  }
  
  /**
   * Unique identifier of the operational entity.
   * @return id
   **/
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public BigDecimal getId() {
    return id;
  }


  /**
   * GLCS (Global Limit Code System). Internal and global unique reference of the Legal Entity.
   * @return glcs
   **/
  @JsonProperty(JSON_PROPERTY_GLCS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getGlcs() {
    return glcs;
  }



  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityResponse {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    glcs: ").append(toIndentedString(glcs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

