/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.client;

import jakarta.ws.rs.core.Response;

public class ApiException extends Exception {

  private static final long serialVersionUID = 1L;
  private Response response;

  public ApiException() {
    super();
  }

  public ApiException(Response response) {
    super("Api response has status code " + response.getStatus());
    this.response = response;
  }

  public Response getResponse() {
    return this.response;
  }
}
