/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.client;

import es.santander.scib.gboboxaccount.rest.dto.Health;

import jakarta.ws.rs.*;
import jakarta.validation.constraints.*;
import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * BOX Accounts
 *
 * <p>The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 */

@RegisterRestClient(configKey="scib-api-gateway")
@RegisterProvider(ApiExceptionMapper.class)
@Path("/health")
public interface LivenessReadinessApi  {

    /**
     * Retrieve the liveness and the readiness of the service.
     *
     * Retrieve the liveness and the readiness of the service.
     *
     */
    @GET
    
    @Produces({ "application/json" })
    Health retrieveHealth(@HeaderParam("authorization")  @NotNull String authorization, @HeaderParam("x-santander-client-id")  @NotNull String xSantanderClientId, @HeaderParam("x-santander-device")  String xSantanderDevice, @HeaderParam("accept-language")  String acceptLanguage, @HeaderParam("if-none-match")  String ifNoneMatch, @HeaderParam("if-match")  String ifMatch, @HeaderParam("x-b3-traceid")  String xB3Traceid, @HeaderParam("x-b3-parentspanid")  String xB3Parentspanid, @HeaderParam("x-b3-spanid")  String xB3Spanid, @HeaderParam("x-b3-sampled")  String xB3Sampled) throws ApiException, ProcessingException;
}
