/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;

@JsonPropertyOrder({
  AccountingMovementDetail.JSON_PROPERTY_CONTRACT,
  AccountingMovementDetail.JSON_PROPERTY_DESCRIPTION1
})
/**
  * Data structure containing information about an accounting movement detail
  */

public class AccountingMovementDetail  implements Serializable {
  
  public static final String JSON_PROPERTY_CONTRACT = "contract";
  
  private Contract contract;

  public static final String JSON_PROPERTY_DESCRIPTION1 = "description1";
 /**
  * Line 1 of the accounting movement detail
  */
  
  private String description1;

  /**
   * Get contract
   * @return contract
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Contract getContract() {
    return contract;
  }

  /**
   * Set contract
   */
  @JsonProperty(JSON_PROPERTY_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContract(Contract contract) {
    this.contract = contract;
  }

  public AccountingMovementDetail contract(Contract contract) {
    this.contract = contract;
    return this;
  }

  /**
   * Line 1 of the accounting movement detail
   * @return description1
   **/
 @Size(max=125)  @JsonProperty(JSON_PROPERTY_DESCRIPTION1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription1() {
    return description1;
  }

  /**
   * Set description1
   */
  @JsonProperty(JSON_PROPERTY_DESCRIPTION1)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDescription1(String description1) {
    this.description1 = description1;
  }

  public AccountingMovementDetail description1(String description1) {
    this.description1 = description1;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountingMovementDetail {\n");
    
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    description1: ").append(toIndentedString(description1)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

