/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.constraints.*;

@JsonPropertyOrder({
  AccountIdentification.JSON_PROPERTY_DISPLAY_NAME,
  AccountIdentification.JSON_PROPERTY_NICK_NAME
})
/**
  * Data structure containing information related to account identification
  */

public class AccountIdentification  implements Serializable {
  
  public static final String JSON_PROPERTY_DISPLAY_NAME = "displayName";
 /**
  * Displayed account name
  */
  
  private String displayName;

  public static final String JSON_PROPERTY_NICK_NAME = "nickName";
 /**
  * Account nickname. Also known as mnemonic.
  */
  
  private String nickName;

  /**
   * Displayed account name
   * @return displayName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDisplayName() {
    return displayName;
  }

  /**
   * Set displayName
   */
  @JsonProperty(JSON_PROPERTY_DISPLAY_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDisplayName(String displayName) {
    this.displayName = displayName;
  }

  public AccountIdentification displayName(String displayName) {
    this.displayName = displayName;
    return this;
  }

  /**
   * Account nickname. Also known as mnemonic.
   * @return nickName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_NICK_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getNickName() {
    return nickName;
  }

  /**
   * Set nickName
   */
  @JsonProperty(JSON_PROPERTY_NICK_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  public AccountIdentification nickName(String nickName) {
    this.nickName = nickName;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AccountIdentification {\n");
    
    sb.append("    displayName: ").append(toIndentedString(displayName)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

