/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  AlertData.JSON_PROPERTY_ALERT_CONFIG,
  AlertData.JSON_PROPERTY_IS_ALERT_CONFIG
})
/**
  * Data structure containing information related to DTCC Alert application. Alert application is an online global database for the maintenance and communication of accounts and SSIs.
  */

public class AlertData  implements Serializable {
  
  public static final String JSON_PROPERTY_ALERT_CONFIG = "alertConfig";
 /**
  * Array containing the sub-account's Alert acronyms and access codes used to retrieve Settlement instructions for each family.
  */
  
  private List<@Valid AlertConfigInner> alertConfig = null;

  public static final String JSON_PROPERTY_IS_ALERT_CONFIG = "isAlertConfig";
 /**
  * Wheter the Sub-Account is being synchronized with DTCC Alert application.
  */
  
  private Boolean isAlertConfig;

  /**
   * Array containing the sub-account&#39;s Alert acronyms and access codes used to retrieve Settlement instructions for each family.
   * @return alertConfig
   **/
  @JsonProperty(JSON_PROPERTY_ALERT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid AlertConfigInner> getAlertConfig() {
    return alertConfig;
  }

  /**
   * Set alertConfig
   */
  @JsonProperty(JSON_PROPERTY_ALERT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAlertConfig(List<@Valid AlertConfigInner> alertConfig) {
    this.alertConfig = alertConfig;
  }

  public AlertData alertConfig(List<@Valid AlertConfigInner> alertConfig) {
    this.alertConfig = alertConfig;
    return this;
  }

  public AlertData addAlertConfigItem(AlertConfigInner alertConfigItem) {
    if (this.alertConfig == null) {
      this.alertConfig = new ArrayList<>();
    }
    this.alertConfig.add(alertConfigItem);
    return this;
  }

  /**
   * Wheter the Sub-Account is being synchronized with DTCC Alert application.
   * @return isAlertConfig
   **/
  @JsonProperty(JSON_PROPERTY_IS_ALERT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsAlertConfig() {
    return isAlertConfig;
  }

  /**
   * Set isAlertConfig
   */
  @JsonProperty(JSON_PROPERTY_IS_ALERT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAlertConfig(Boolean isAlertConfig) {
    this.isAlertConfig = isAlertConfig;
  }

  public AlertData isAlertConfig(Boolean isAlertConfig) {
    this.isAlertConfig = isAlertConfig;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertData {\n");
    
    sb.append("    alertConfig: ").append(toIndentedString(alertConfig)).append("\n");
    sb.append("    isAlertConfig: ").append(toIndentedString(isAlertConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

