/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;

@JsonPropertyOrder({
  AlertAcronyms.JSON_PROPERTY_ACRONYMS,
  AlertAcronyms.JSON_PROPERTY_IS_ALERT_CONFIG
})
/**
  * Data structure containing information related to DTCC Alert application. Alert application is an online global database for the maintenance and communication of accounts and SSIs.
  */

public class AlertAcronyms  implements Serializable {
  
  public static final String JSON_PROPERTY_ACRONYMS = "acronyms";
 /**
  * Array of client identification codes in Alert application.
  */
  
  private List<String> acronyms = null;

  public static final String JSON_PROPERTY_IS_ALERT_CONFIG = "isAlertConfig";
 /**
  * Whether the Account is being synchronized with DTCC Alert application.
  */
  
  private Boolean isAlertConfig;

  /**
   * Array of client identification codes in Alert application.
   * @return acronyms
   **/
  @JsonProperty(JSON_PROPERTY_ACRONYMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<String> getAcronyms() {
    return acronyms;
  }

  /**
   * Set acronyms
   */
  @JsonProperty(JSON_PROPERTY_ACRONYMS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAcronyms(List<String> acronyms) {
    this.acronyms = acronyms;
  }

  public AlertAcronyms acronyms(List<String> acronyms) {
    this.acronyms = acronyms;
    return this;
  }

  public AlertAcronyms addAcronymsItem(String acronymsItem) {
    if (this.acronyms == null) {
      this.acronyms = new ArrayList<>();
    }
    this.acronyms.add(acronymsItem);
    return this;
  }

  /**
   * Whether the Account is being synchronized with DTCC Alert application.
   * @return isAlertConfig
   **/
  @JsonProperty(JSON_PROPERTY_IS_ALERT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsAlertConfig() {
    return isAlertConfig;
  }

  /**
   * Set isAlertConfig
   */
  @JsonProperty(JSON_PROPERTY_IS_ALERT_CONFIG)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAlertConfig(Boolean isAlertConfig) {
    this.isAlertConfig = isAlertConfig;
  }

  public AlertAcronyms isAlertConfig(Boolean isAlertConfig) {
    this.isAlertConfig = isAlertConfig;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AlertAcronyms {\n");
    
    sb.append("    acronyms: ").append(toIndentedString(acronyms)).append("\n");
    sb.append("    isAlertConfig: ").append(toIndentedString(isAlertConfig)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

