/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Period.JSON_PROPERTY_END_DATE,
  Period.JSON_PROPERTY_START_DATE
})
/**
  * Data structure containing period information
  */

public class Period  implements Serializable {
  
  public static final String JSON_PROPERTY_END_DATE = "endDate";
 /**
  * Date when the period ends.  The value uses the complete data format defined in ISO 8601:  'YYYY-MM-DD'  Where: - YYYY: 4-digit year - MM: 2-digit month (for example, 01 = January) - DD: 2-digit day of the month (01 through 31)
  */
  
  private Date endDate;

  public static final String JSON_PROPERTY_START_DATE = "startDate";
 /**
  * Date when the period starts.  The value uses the complete data format defined in ISO 8601:  'YYYY-MM-DD'  Where: - YYYY: 4-digit year - MM: 2-digit month (for example, 01 = January) - DD: 2-digit day of the month (01 through 31)
  */
  
  private Date startDate;

  /**
   * Date when the period ends.  The value uses the complete data format defined in ISO 8601:  &#39;YYYY-MM-DD&#39;  Where: - YYYY: 4-digit year - MM: 2-digit month (for example, 01 &#x3D; January) - DD: 2-digit day of the month (01 through 31)
   * @return endDate
   **/
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Date getEndDate() {
    return endDate;
  }

  /**
   * Set endDate
   */
  @JsonProperty(JSON_PROPERTY_END_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEndDate(Date endDate) {
    this.endDate = endDate;
  }

  public Period endDate(Date endDate) {
    this.endDate = endDate;
    return this;
  }

  /**
   * Date when the period starts.  The value uses the complete data format defined in ISO 8601:  &#39;YYYY-MM-DD&#39;  Where: - YYYY: 4-digit year - MM: 2-digit month (for example, 01 &#x3D; January) - DD: 2-digit day of the month (01 through 31)
   * @return startDate
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Date getStartDate() {
    return startDate;
  }

  /**
   * Set startDate
   */
  @JsonProperty(JSON_PROPERTY_START_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStartDate(Date startDate) {
    this.startDate = startDate;
  }

  public Period startDate(Date startDate) {
    this.startDate = startDate;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Period {\n");
    
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

