/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboboxaccount.rest.dto.PersonName;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Person.JSON_PROPERTY_PERSON_NAME
})
/**
  * Data structure containing information about a natural person
  */

public class Person  implements Serializable {
  
  public static final String JSON_PROPERTY_PERSON_NAME = "personName";
  
  private PersonName personName;

  /**
   * Get personName
   * @return personName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_PERSON_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public PersonName getPersonName() {
    return personName;
  }

  /**
   * Set personName
   */
  @JsonProperty(JSON_PROPERTY_PERSON_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPersonName(PersonName personName) {
    this.personName = personName;
  }

  public Person personName(PersonName personName) {
    this.personName = personName;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Person {\n");
    
    sb.append("    personName: ").append(toIndentedString(personName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

