/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  PersonName.JSON_PROPERTY_FULL_NAME,
  PersonName.JSON_PROPERTY_NICK_NAME
})
/**
  * Data structure containing information about a person's name. The information included in the data structure relates to the name by which the person is known and that is commonly used to identify the person.
  */

public class PersonName  implements Serializable {
  
  public static final String JSON_PROPERTY_FULL_NAME = "fullName";
 /**
  * Person's full name
  */
  
  private String fullName;

  public static final String JSON_PROPERTY_NICK_NAME = "nickName";
 /**
  * Person's nickname.  The value can be alphanumeric and can include periods, commas, spaces, dashes, single quotes, and apostrophes.
  */
  
  private String nickName;

  /**
   * Person&#39;s full name
   * @return fullName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getFullName() {
    return fullName;
  }

  /**
   * Set fullName
   */
  @JsonProperty(JSON_PROPERTY_FULL_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setFullName(String fullName) {
    this.fullName = fullName;
  }

  public PersonName fullName(String fullName) {
    this.fullName = fullName;
    return this;
  }

  /**
   * Person&#39;s nickname.  The value can be alphanumeric and can include periods, commas, spaces, dashes, single quotes, and apostrophes.
   * @return nickName
   **/
  @JsonProperty(JSON_PROPERTY_NICK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getNickName() {
    return nickName;
  }

  /**
   * Set nickName
   */
  @JsonProperty(JSON_PROPERTY_NICK_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNickName(String nickName) {
    this.nickName = nickName;
  }

  public PersonName nickName(String nickName) {
    this.nickName = nickName;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonName {\n");
    
    sb.append("    fullName: ").append(toIndentedString(fullName)).append("\n");
    sb.append("    nickName: ").append(toIndentedString(nickName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

