/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboboxaccount.rest.dto.CashFlow;
import es.santander.scib.gboboxaccount.rest.dto.StandardSettlementInstructionsMethodPaymentSystem;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StandardSettlementInstructionsMethod.JSON_PROPERTY_CASH_FLOW,
  StandardSettlementInstructionsMethod.JSON_PROPERTY_DIRECT_METHOD_TYPE,
  StandardSettlementInstructionsMethod.JSON_PROPERTY_METHOD_TYPE,
  StandardSettlementInstructionsMethod.JSON_PROPERTY_PAYMENT_SYSTEM
})
@JsonTypeName("StandardSettlementInstructions_method")
/**
  * Data structure containing information about a settlement method to which the settlement instructions correspond
  */

public class StandardSettlementInstructionsMethod  implements Serializable {
  
  public static final String JSON_PROPERTY_CASH_FLOW = "cashFlow";
  
  private CashFlow cashFlow;

  public static final String JSON_PROPERTY_DIRECT_METHOD_TYPE = "directMethodType";
 /**
  * Direct settlement method type
  */
  
  private String directMethodType;

  public static final String JSON_PROPERTY_METHOD_TYPE = "methodType";
 /**
  * Settlement method type
  */
  
  private String methodType;

  public static final String JSON_PROPERTY_PAYMENT_SYSTEM = "paymentSystem";
  
  private StandardSettlementInstructionsMethodPaymentSystem paymentSystem;

  /**
   * Get cashFlow
   * @return cashFlow
   **/
  @JsonProperty(JSON_PROPERTY_CASH_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public CashFlow getCashFlow() {
    return cashFlow;
  }

  /**
   * Set cashFlow
   */
  @JsonProperty(JSON_PROPERTY_CASH_FLOW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCashFlow(CashFlow cashFlow) {
    this.cashFlow = cashFlow;
  }

  public StandardSettlementInstructionsMethod cashFlow(CashFlow cashFlow) {
    this.cashFlow = cashFlow;
    return this;
  }

  /**
   * Direct settlement method type
   * @return directMethodType
   **/
  @JsonProperty(JSON_PROPERTY_DIRECT_METHOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDirectMethodType() {
    return directMethodType;
  }

  /**
   * Set directMethodType
   */
  @JsonProperty(JSON_PROPERTY_DIRECT_METHOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDirectMethodType(String directMethodType) {
    this.directMethodType = directMethodType;
  }

  public StandardSettlementInstructionsMethod directMethodType(String directMethodType) {
    this.directMethodType = directMethodType;
    return this;
  }

  /**
   * Settlement method type
   * @return methodType
   **/
  @JsonProperty(JSON_PROPERTY_METHOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getMethodType() {
    return methodType;
  }

  /**
   * Set methodType
   */
  @JsonProperty(JSON_PROPERTY_METHOD_TYPE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethodType(String methodType) {
    this.methodType = methodType;
  }

  public StandardSettlementInstructionsMethod methodType(String methodType) {
    this.methodType = methodType;
    return this;
  }

  /**
   * Get paymentSystem
   * @return paymentSystem
   **/
  @JsonProperty(JSON_PROPERTY_PAYMENT_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StandardSettlementInstructionsMethodPaymentSystem getPaymentSystem() {
    return paymentSystem;
  }

  /**
   * Set paymentSystem
   */
  @JsonProperty(JSON_PROPERTY_PAYMENT_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentSystem(StandardSettlementInstructionsMethodPaymentSystem paymentSystem) {
    this.paymentSystem = paymentSystem;
  }

  public StandardSettlementInstructionsMethod paymentSystem(StandardSettlementInstructionsMethodPaymentSystem paymentSystem) {
    this.paymentSystem = paymentSystem;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardSettlementInstructionsMethod {\n");
    
    sb.append("    cashFlow: ").append(toIndentedString(cashFlow)).append("\n");
    sb.append("    directMethodType: ").append(toIndentedString(directMethodType)).append("\n");
    sb.append("    methodType: ").append(toIndentedString(methodType)).append("\n");
    sb.append("    paymentSystem: ").append(toIndentedString(paymentSystem)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

