/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboboxaccount.rest.dto.Party;
import es.santander.scib.gboboxaccount.rest.dto.StandardSettlementInstructionsSettlementPartiesInnerAccountsInner;
import es.santander.scib.gboboxaccount.rest.dto.StandardSettlementInstructionsSettlementPartiesInnerSpecialInstructions;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StandardSettlementInstructionsSettlementPartiesInner.JSON_PROPERTY_ACCOUNTS,
  StandardSettlementInstructionsSettlementPartiesInner.JSON_PROPERTY_PARTY,
  StandardSettlementInstructionsSettlementPartiesInner.JSON_PROPERTY_SPECIAL_INSTRUCTIONS
})
@JsonTypeName("StandardSettlementInstructions_settlementParties_inner")
/**
  * Data structure containing information about a counterparty
  */

public class StandardSettlementInstructionsSettlementPartiesInner  implements Serializable {
  
  public static final String JSON_PROPERTY_ACCOUNTS = "accounts";
 /**
  * Array of accounts
  */
  
  private List<@Valid StandardSettlementInstructionsSettlementPartiesInnerAccountsInner> accounts = null;

  public static final String JSON_PROPERTY_PARTY = "party";
  
  private Party party;

  public static final String JSON_PROPERTY_SPECIAL_INSTRUCTIONS = "specialInstructions";
  
  private StandardSettlementInstructionsSettlementPartiesInnerSpecialInstructions specialInstructions;

  /**
   * Array of accounts
   * @return accounts
   **/
  @JsonProperty(JSON_PROPERTY_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid StandardSettlementInstructionsSettlementPartiesInnerAccountsInner> getAccounts() {
    return accounts;
  }

  /**
   * Set accounts
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccounts(List<@Valid StandardSettlementInstructionsSettlementPartiesInnerAccountsInner> accounts) {
    this.accounts = accounts;
  }

  public StandardSettlementInstructionsSettlementPartiesInner accounts(List<@Valid StandardSettlementInstructionsSettlementPartiesInnerAccountsInner> accounts) {
    this.accounts = accounts;
    return this;
  }

  public StandardSettlementInstructionsSettlementPartiesInner addAccountsItem(StandardSettlementInstructionsSettlementPartiesInnerAccountsInner accountsItem) {
    if (this.accounts == null) {
      this.accounts = new ArrayList<>();
    }
    this.accounts.add(accountsItem);
    return this;
  }

  /**
   * Get party
   * @return party
   **/
  @JsonProperty(JSON_PROPERTY_PARTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Party getParty() {
    return party;
  }

  /**
   * Set party
   */
  @JsonProperty(JSON_PROPERTY_PARTY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setParty(Party party) {
    this.party = party;
  }

  public StandardSettlementInstructionsSettlementPartiesInner party(Party party) {
    this.party = party;
    return this;
  }

  /**
   * Get specialInstructions
   * @return specialInstructions
   **/
  @JsonProperty(JSON_PROPERTY_SPECIAL_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StandardSettlementInstructionsSettlementPartiesInnerSpecialInstructions getSpecialInstructions() {
    return specialInstructions;
  }

  /**
   * Set specialInstructions
   */
  @JsonProperty(JSON_PROPERTY_SPECIAL_INSTRUCTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSpecialInstructions(StandardSettlementInstructionsSettlementPartiesInnerSpecialInstructions specialInstructions) {
    this.specialInstructions = specialInstructions;
  }

  public StandardSettlementInstructionsSettlementPartiesInner specialInstructions(StandardSettlementInstructionsSettlementPartiesInnerSpecialInstructions specialInstructions) {
    this.specialInstructions = specialInstructions;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardSettlementInstructionsSettlementPartiesInner {\n");
    
    sb.append("    accounts: ").append(toIndentedString(accounts)).append("\n");
    sb.append("    party: ").append(toIndentedString(party)).append("\n");
    sb.append("    specialInstructions: ").append(toIndentedString(specialInstructions)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

