/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StandardSettlementInstructionsMethodPaymentSystem.JSON_PROPERTY_TYPE_CODE,
  StandardSettlementInstructionsMethodPaymentSystem.JSON_PROPERTY_TYPE_DESCRIPTION
})
@JsonTypeName("StandardSettlementInstructions_method_paymentSystem")
/**
  * Data structure containing information about the payment system to which the settlement instructions correspond
  */

public class StandardSettlementInstructionsMethodPaymentSystem  implements Serializable {
  
  public static final String JSON_PROPERTY_TYPE_CODE = "typeCode";
 /**
  * The code of the payment system to which the settlement instructions correspond
  */
  
  private String typeCode;

  public static final String JSON_PROPERTY_TYPE_DESCRIPTION = "typeDescription";
 /**
  * The description of the payment system to which the settlement instructions correspond
  */
  
  private String typeDescription;

  /**
   * The code of the payment system to which the settlement instructions correspond
   * @return typeCode
   **/
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTypeCode() {
    return typeCode;
  }

  /**
   * Set typeCode
   */
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeCode(String typeCode) {
    this.typeCode = typeCode;
  }

  public StandardSettlementInstructionsMethodPaymentSystem typeCode(String typeCode) {
    this.typeCode = typeCode;
    return this;
  }

  /**
   * The description of the payment system to which the settlement instructions correspond
   * @return typeDescription
   **/
  @JsonProperty(JSON_PROPERTY_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getTypeDescription() {
    return typeDescription;
  }

  /**
   * Set typeDescription
   */
  @JsonProperty(JSON_PROPERTY_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeDescription(String typeDescription) {
    this.typeDescription = typeDescription;
  }

  public StandardSettlementInstructionsMethodPaymentSystem typeDescription(String typeDescription) {
    this.typeDescription = typeDescription;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardSettlementInstructionsMethodPaymentSystem {\n");
    
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("    typeDescription: ").append(toIndentedString(typeDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

