/**
 * BOX Accounts
 * The API will be used by all the systems in different markets to enrich Back Office Express (BOX) Security Accounts data model in the onboarding process of clients that want to start doing business with Santander, meaning that the API will be called to insert details of the accounts, sub accounts and settlement instructions. It will be used to create and update data during the ongoing process. Also, it will be possible to retrieve information from BOX Accounts, so other systems can use the information that is stored in it. This API was initially thought to industrialize the process of manual insertion by users.
 *
 * The version of the OpenAPI document: 3.0.0
 * Contact: francisco.gonzalezhernandez@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboboxaccount.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboboxaccount.rest.dto.AccountingMovement;
import es.santander.scib.gboboxaccount.rest.dto.Amount;
import es.santander.scib.gboboxaccount.rest.dto.Currency;
import es.santander.scib.gboboxaccount.rest.dto.Period;
import es.santander.scib.gboboxaccount.rest.dto.Product;
import es.santander.scib.gboboxaccount.rest.dto.StandardSettlementInstructionsMethod;
import es.santander.scib.gboboxaccount.rest.dto.StandardSettlementInstructionsSettlementPartiesInner;
import es.santander.scib.gboboxaccount.rest.dto.StandardSettlementInstructionsStandardSettlementInstructionsParent;
import es.santander.scib.gboboxaccount.rest.dto.System;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StandardSettlementInstructions.JSON_PROPERTY_ACCOUNTING_MOVEMENTS,
  StandardSettlementInstructions.JSON_PROPERTY_CURRENCY,
  StandardSettlementInstructions.JSON_PROPERTY_IS_ACTIVE,
  StandardSettlementInstructions.JSON_PROPERTY_IS_DEFAULT,
  StandardSettlementInstructions.JSON_PROPERTY_MAXIMUM_AMOUNT,
  StandardSettlementInstructions.JSON_PROPERTY_METHOD,
  StandardSettlementInstructions.JSON_PROPERTY_MINIMUM_AMOUNT,
  StandardSettlementInstructions.JSON_PROPERTY_OPERATION_CODE,
  StandardSettlementInstructions.JSON_PROPERTY_PERIOD,
  StandardSettlementInstructions.JSON_PROPERTY_PRIORITY,
  StandardSettlementInstructions.JSON_PROPERTY_PRODUCT,
  StandardSettlementInstructions.JSON_PROPERTY_PURPOSE,
  StandardSettlementInstructions.JSON_PROPERTY_SETTLEMENT_PARTIES,
  StandardSettlementInstructions.JSON_PROPERTY_SOURCE_SYSTEM,
  StandardSettlementInstructions.JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_ID,
  StandardSettlementInstructions.JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_PARENT,
  StandardSettlementInstructions.JSON_PROPERTY_TYPE_CODE
})
/**
  * Data structure containing specific information about standard settlement instructions. The instructions are used for cash or securities.
  */

public class StandardSettlementInstructions  implements Serializable {
  
  public static final String JSON_PROPERTY_ACCOUNTING_MOVEMENTS = "accountingMovements";
 /**
  * Array of accounting movements for the settlement instructions
  */
  
  private List<@Valid AccountingMovement> accountingMovements = null;

  public static final String JSON_PROPERTY_CURRENCY = "currency";
  
  private Currency currency;

  public static final String JSON_PROPERTY_IS_ACTIVE = "isActive";
 /**
  * Whether the standard settlement instructions are active
  */
  
  private Boolean isActive;

  public static final String JSON_PROPERTY_IS_DEFAULT = "isDefault";
 /**
  * Whether the standard settlement instructions are the default instructions
  */
  
  private Boolean isDefault;

  public static final String JSON_PROPERTY_MAXIMUM_AMOUNT = "maximumAmount";
  
  private Amount maximumAmount;

  public static final String JSON_PROPERTY_METHOD = "method";
  
  private StandardSettlementInstructionsMethod method;

  public static final String JSON_PROPERTY_MINIMUM_AMOUNT = "minimumAmount";
  
  private Amount minimumAmount;

  public enum OperationCodeEnum {

    PAY(String.valueOf("PAY")), RECEIVE(String.valueOf("RECEIVE")), BOTH(String.valueOf("BOTH"));


    String value;

    OperationCodeEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static OperationCodeEnum fromValue(String value) {
            for (OperationCodeEnum b : OperationCodeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_OPERATION_CODE = "operationCode";
 /**
  * Code for the direction that the standard settlement instructions accept for their operation flows
  */
  
  private OperationCodeEnum operationCode;

  public static final String JSON_PROPERTY_PERIOD = "period";
  
  private Period period;

  public static final String JSON_PROPERTY_PRIORITY = "priority";
 /**
  * Priority order of the standard settlement instructions when multiple instructions with the same criteria exist within the same account or sub-account.  The lowest value represents the highest priority.
  */
  
  private String priority;

  public static final String JSON_PROPERTY_PRODUCT = "product";
  
  private Product product;

  public static final String JSON_PROPERTY_PURPOSE = "purpose";
 /**
  * Purpose of the settlement to which the instructions are applied
  */
  
  private String purpose;

  public static final String JSON_PROPERTY_SETTLEMENT_PARTIES = "settlementParties";
 /**
  * Array of parties related to the instruction settlement
  */
  
  private List<@Valid StandardSettlementInstructionsSettlementPartiesInner> settlementParties = new ArrayList<>();

  public static final String JSON_PROPERTY_SOURCE_SYSTEM = "sourceSystem";
  
  private System sourceSystem;

  public static final String JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_ID = "standardSettlementInstructionsId";
 /**
  * Unique ID for the standard settlement instructions
  */
  
  private String standardSettlementInstructionsId;

  public static final String JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_PARENT = "standardSettlementInstructionsParent";
  
  private StandardSettlementInstructionsStandardSettlementInstructionsParent standardSettlementInstructionsParent;

  public enum TypeCodeEnum {

    CASH(String.valueOf("CASH")), SECURITIES(String.valueOf("SECURITIES")), SECURITIES_AGAINST_PAYMENT(String.valueOf("SECURITIES_AGAINST_PAYMENT")), SECURITIES_FREE_PAYMENT(String.valueOf("SECURITIES_FREE_PAYMENT"));


    String value;

    TypeCodeEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static TypeCodeEnum fromValue(String value) {
            for (TypeCodeEnum b : TypeCodeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_TYPE_CODE = "typeCode";
 /**
  * Code for the standard settlement instruction type
  */
  
  private TypeCodeEnum typeCode;

  public StandardSettlementInstructions() {
  }

 @JsonCreator
  public StandardSettlementInstructions(
    @JsonProperty(value = JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_ID, required = true) String standardSettlementInstructionsId
  ) {
    this.standardSettlementInstructionsId = standardSettlementInstructionsId;
  }
  
  /**
   * Array of accounting movements for the settlement instructions
   * @return accountingMovements
   **/
  @JsonProperty(JSON_PROPERTY_ACCOUNTING_MOVEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid AccountingMovement> getAccountingMovements() {
    return accountingMovements;
  }

  /**
   * Set accountingMovements
   */
  @JsonProperty(JSON_PROPERTY_ACCOUNTING_MOVEMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAccountingMovements(List<@Valid AccountingMovement> accountingMovements) {
    this.accountingMovements = accountingMovements;
  }

  public StandardSettlementInstructions accountingMovements(List<@Valid AccountingMovement> accountingMovements) {
    this.accountingMovements = accountingMovements;
    return this;
  }

  public StandardSettlementInstructions addAccountingMovementsItem(AccountingMovement accountingMovementsItem) {
    if (this.accountingMovements == null) {
      this.accountingMovements = new ArrayList<>();
    }
    this.accountingMovements.add(accountingMovementsItem);
    return this;
  }

  /**
   * Get currency
   * @return currency
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Currency getCurrency() {
    return currency;
  }

  /**
   * Set currency
   */
  @JsonProperty(JSON_PROPERTY_CURRENCY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCurrency(Currency currency) {
    this.currency = currency;
  }

  public StandardSettlementInstructions currency(Currency currency) {
    this.currency = currency;
    return this;
  }

  /**
   * Whether the standard settlement instructions are active
   * @return isActive
   **/
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsActive() {
    return isActive;
  }

  /**
   * Set isActive
   */
  @JsonProperty(JSON_PROPERTY_IS_ACTIVE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsActive(Boolean isActive) {
    this.isActive = isActive;
  }

  public StandardSettlementInstructions isActive(Boolean isActive) {
    this.isActive = isActive;
    return this;
  }

  /**
   * Whether the standard settlement instructions are the default instructions
   * @return isDefault
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Boolean getIsDefault() {
    return isDefault;
  }

  /**
   * Set isDefault
   */
  @JsonProperty(JSON_PROPERTY_IS_DEFAULT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIsDefault(Boolean isDefault) {
    this.isDefault = isDefault;
  }

  public StandardSettlementInstructions isDefault(Boolean isDefault) {
    this.isDefault = isDefault;
    return this;
  }

  /**
   * Get maximumAmount
   * @return maximumAmount
   **/
  @JsonProperty(JSON_PROPERTY_MAXIMUM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getMaximumAmount() {
    return maximumAmount;
  }

  /**
   * Set maximumAmount
   */
  @JsonProperty(JSON_PROPERTY_MAXIMUM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaximumAmount(Amount maximumAmount) {
    this.maximumAmount = maximumAmount;
  }

  public StandardSettlementInstructions maximumAmount(Amount maximumAmount) {
    this.maximumAmount = maximumAmount;
    return this;
  }

  /**
   * Get method
   * @return method
   **/
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StandardSettlementInstructionsMethod getMethod() {
    return method;
  }

  /**
   * Set method
   */
  @JsonProperty(JSON_PROPERTY_METHOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMethod(StandardSettlementInstructionsMethod method) {
    this.method = method;
  }

  public StandardSettlementInstructions method(StandardSettlementInstructionsMethod method) {
    this.method = method;
    return this;
  }

  /**
   * Get minimumAmount
   * @return minimumAmount
   **/
  @JsonProperty(JSON_PROPERTY_MINIMUM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Amount getMinimumAmount() {
    return minimumAmount;
  }

  /**
   * Set minimumAmount
   */
  @JsonProperty(JSON_PROPERTY_MINIMUM_AMOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinimumAmount(Amount minimumAmount) {
    this.minimumAmount = minimumAmount;
  }

  public StandardSettlementInstructions minimumAmount(Amount minimumAmount) {
    this.minimumAmount = minimumAmount;
    return this;
  }

  /**
   * Code for the direction that the standard settlement instructions accept for their operation flows
   * @return operationCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public OperationCodeEnum getOperationCode() {
    return operationCode;
  }

  /**
   * Set operationCode
   */
  @JsonProperty(JSON_PROPERTY_OPERATION_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOperationCode(OperationCodeEnum operationCode) {
    this.operationCode = operationCode;
  }

  public StandardSettlementInstructions operationCode(OperationCodeEnum operationCode) {
    this.operationCode = operationCode;
    return this;
  }

  /**
   * Get period
   * @return period
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Period getPeriod() {
    return period;
  }

  /**
   * Set period
   */
  @JsonProperty(JSON_PROPERTY_PERIOD)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setPeriod(Period period) {
    this.period = period;
  }

  public StandardSettlementInstructions period(Period period) {
    this.period = period;
    return this;
  }

  /**
   * Priority order of the standard settlement instructions when multiple instructions with the same criteria exist within the same account or sub-account.  The lowest value represents the highest priority.
   * @return priority
   **/
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPriority() {
    return priority;
  }

  /**
   * Set priority
   */
  @JsonProperty(JSON_PROPERTY_PRIORITY)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPriority(String priority) {
    this.priority = priority;
  }

  public StandardSettlementInstructions priority(String priority) {
    this.priority = priority;
    return this;
  }

  /**
   * Get product
   * @return product
   **/
  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Product getProduct() {
    return product;
  }

  /**
   * Set product
   */
  @JsonProperty(JSON_PROPERTY_PRODUCT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setProduct(Product product) {
    this.product = product;
  }

  public StandardSettlementInstructions product(Product product) {
    this.product = product;
    return this;
  }

  /**
   * Purpose of the settlement to which the instructions are applied
   * @return purpose
   **/
  @JsonProperty(JSON_PROPERTY_PURPOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getPurpose() {
    return purpose;
  }

  /**
   * Set purpose
   */
  @JsonProperty(JSON_PROPERTY_PURPOSE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPurpose(String purpose) {
    this.purpose = purpose;
  }

  public StandardSettlementInstructions purpose(String purpose) {
    this.purpose = purpose;
    return this;
  }

  /**
   * Array of parties related to the instruction settlement
   * @return settlementParties
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_PARTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid StandardSettlementInstructionsSettlementPartiesInner> getSettlementParties() {
    return settlementParties;
  }

  /**
   * Set settlementParties
   */
  @JsonProperty(JSON_PROPERTY_SETTLEMENT_PARTIES)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setSettlementParties(List<@Valid StandardSettlementInstructionsSettlementPartiesInner> settlementParties) {
    this.settlementParties = settlementParties;
  }

  public StandardSettlementInstructions settlementParties(List<@Valid StandardSettlementInstructionsSettlementPartiesInner> settlementParties) {
    this.settlementParties = settlementParties;
    return this;
  }

  public StandardSettlementInstructions addSettlementPartiesItem(StandardSettlementInstructionsSettlementPartiesInner settlementPartiesItem) {
    if (this.settlementParties == null) {
      this.settlementParties = new ArrayList<>();
    }
    this.settlementParties.add(settlementPartiesItem);
    return this;
  }

  /**
   * Get sourceSystem
   * @return sourceSystem
   **/
  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public System getSourceSystem() {
    return sourceSystem;
  }

  /**
   * Set sourceSystem
   */
  @JsonProperty(JSON_PROPERTY_SOURCE_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSourceSystem(System sourceSystem) {
    this.sourceSystem = sourceSystem;
  }

  public StandardSettlementInstructions sourceSystem(System sourceSystem) {
    this.sourceSystem = sourceSystem;
    return this;
  }

  /**
   * Unique ID for the standard settlement instructions
   * @return standardSettlementInstructionsId
   **/
  @JsonProperty(JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_ID)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStandardSettlementInstructionsId() {
    return standardSettlementInstructionsId;
  }


  /**
   * Get standardSettlementInstructionsParent
   * @return standardSettlementInstructionsParent
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_PARENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StandardSettlementInstructionsStandardSettlementInstructionsParent getStandardSettlementInstructionsParent() {
    return standardSettlementInstructionsParent;
  }

  /**
   * Set standardSettlementInstructionsParent
   */
  @JsonProperty(JSON_PROPERTY_STANDARD_SETTLEMENT_INSTRUCTIONS_PARENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStandardSettlementInstructionsParent(StandardSettlementInstructionsStandardSettlementInstructionsParent standardSettlementInstructionsParent) {
    this.standardSettlementInstructionsParent = standardSettlementInstructionsParent;
  }

  public StandardSettlementInstructions standardSettlementInstructionsParent(StandardSettlementInstructionsStandardSettlementInstructionsParent standardSettlementInstructionsParent) {
    this.standardSettlementInstructionsParent = standardSettlementInstructionsParent;
    return this;
  }

  /**
   * Code for the standard settlement instruction type
   * @return typeCode
   **/
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public TypeCodeEnum getTypeCode() {
    return typeCode;
  }

  /**
   * Set typeCode
   */
  @JsonProperty(JSON_PROPERTY_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTypeCode(TypeCodeEnum typeCode) {
    this.typeCode = typeCode;
  }

  public StandardSettlementInstructions typeCode(TypeCodeEnum typeCode) {
    this.typeCode = typeCode;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StandardSettlementInstructions {\n");
    
    sb.append("    accountingMovements: ").append(toIndentedString(accountingMovements)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    isActive: ").append(toIndentedString(isActive)).append("\n");
    sb.append("    isDefault: ").append(toIndentedString(isDefault)).append("\n");
    sb.append("    maximumAmount: ").append(toIndentedString(maximumAmount)).append("\n");
    sb.append("    method: ").append(toIndentedString(method)).append("\n");
    sb.append("    minimumAmount: ").append(toIndentedString(minimumAmount)).append("\n");
    sb.append("    operationCode: ").append(toIndentedString(operationCode)).append("\n");
    sb.append("    period: ").append(toIndentedString(period)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    product: ").append(toIndentedString(product)).append("\n");
    sb.append("    purpose: ").append(toIndentedString(purpose)).append("\n");
    sb.append("    settlementParties: ").append(toIndentedString(settlementParties)).append("\n");
    sb.append("    sourceSystem: ").append(toIndentedString(sourceSystem)).append("\n");
    sb.append("    standardSettlementInstructionsId: ").append(toIndentedString(standardSettlementInstructionsId)).append("\n");
    sb.append("    standardSettlementInstructionsParent: ").append(toIndentedString(standardSettlementInstructionsParent)).append("\n");
    sb.append("    typeCode: ").append(toIndentedString(typeCode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

