/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboentities.rest.dto.DfaEligibleContractParticipantType;
import es.santander.scib.gboentities.rest.dto.DfaOwnershipType;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Dfa.JSON_PROPERTY_OWNERSHIP_TYPE,
  Dfa.JSON_PROPERTY_IS_ELIGIBLE_CONTRACT_PARTICIPANT,
  Dfa.JSON_PROPERTY_ELIGIBLE_CONTRACT_PARTICIPANT_TYPES,
  Dfa.JSON_PROPERTY_HAS_STANDING_OPT_OUT_ANNUAL_FILING,
  Dfa.JSON_PROPERTY_IS_COVERED_FOREX_TRANSACTIONS,
  Dfa.JSON_PROPERTY_IS_COVERED_DERIVATIVE_TRANSACTIONS,
  Dfa.JSON_PROPERTY_IS_ADDITIONAL_PTMM_TRANSACTIONS,
  Dfa.JSON_PROPERTY_HAS_ORAL_DISCLOSURE_PTMM_ELECTION
})
/**
  * Data structure containing Dodd-Frank Wall Street Reform and Consumer Protection Act (DFA)
  */

public class Dfa  implements Serializable {
  
  public static final String JSON_PROPERTY_OWNERSHIP_TYPE = "ownershipType";
  
  private DfaOwnershipType ownershipType;

  public static final String JSON_PROPERTY_IS_ELIGIBLE_CONTRACT_PARTICIPANT = "isEligibleContractParticipant";
 /**
  * Whether the entity is eligible to be a contract participant
  */
  
  private Boolean isEligibleContractParticipant;

  public static final String JSON_PROPERTY_ELIGIBLE_CONTRACT_PARTICIPANT_TYPES = "eligibleContractParticipantTypes";
 /**
  * List of eligible contract participant types.
  */
  
  private List<@Valid DfaEligibleContractParticipantType> eligibleContractParticipantTypes = null;

  public static final String JSON_PROPERTY_HAS_STANDING_OPT_OUT_ANNUAL_FILING = "hasStandingOptOutAnnualFiling";
 /**
  * Whether the operation has a clearing exception, which is decided together with the election for DFA question 'Standing End-User Exception'
  */
  
  private Boolean hasStandingOptOutAnnualFiling;

  public static final String JSON_PROPERTY_IS_COVERED_FOREX_TRANSACTIONS = "isCoveredForexTransactions";
 /**
  * Whether the counterparty has answered 'Yes' to the Questionnaire for Covered Forex Transactions
  */
  
  private Boolean isCoveredForexTransactions;

  public static final String JSON_PROPERTY_IS_COVERED_DERIVATIVE_TRANSACTIONS = "isCoveredDerivativeTransactions";
 /**
  * Whether the counterparty has answered 'Yes' to the Questionnaire for Covered Derivative Transactions
  */
  
  private Boolean isCoveredDerivativeTransactions;

  public static final String JSON_PROPERTY_IS_ADDITIONAL_PTMM_TRANSACTIONS = "isAdditionalPtmmTransactions";
 /**
  * Whether the counterparty has answered 'Yes' to the Questionnaire for Additional Pre-Trade Mid-Market Marks (PTMM) Transactions
  */
  
  private Boolean isAdditionalPtmmTransactions;

  public static final String JSON_PROPERTY_HAS_ORAL_DISCLOSURE_PTMM_ELECTION = "hasOralDisclosurePtmmElection";
 /**
  * Whether the Pre-Trade Mid-Market Marks (PTMM) can be provided to the counterparty orally prior to the execution. Even if the answer is 'Yes', the PTMM must also be provided in written format by the end of the day of execution.
  */
  
  private Boolean hasOralDisclosurePtmmElection;

  /**
   * Get ownershipType
   * @return ownershipType
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_OWNERSHIP_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DfaOwnershipType getOwnershipType() {
    return ownershipType;
  }

  /**
   * Set ownershipType
   */
  @JsonProperty(JSON_PROPERTY_OWNERSHIP_TYPE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setOwnershipType(DfaOwnershipType ownershipType) {
    this.ownershipType = ownershipType;
  }

  public Dfa ownershipType(DfaOwnershipType ownershipType) {
    this.ownershipType = ownershipType;
    return this;
  }

  /**
   * Whether the entity is eligible to be a contract participant
   * @return isEligibleContractParticipant
   **/
  @JsonProperty(JSON_PROPERTY_IS_ELIGIBLE_CONTRACT_PARTICIPANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsEligibleContractParticipant() {
    return isEligibleContractParticipant;
  }

  /**
   * Set isEligibleContractParticipant
   */
  @JsonProperty(JSON_PROPERTY_IS_ELIGIBLE_CONTRACT_PARTICIPANT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsEligibleContractParticipant(Boolean isEligibleContractParticipant) {
    this.isEligibleContractParticipant = isEligibleContractParticipant;
  }

  public Dfa isEligibleContractParticipant(Boolean isEligibleContractParticipant) {
    this.isEligibleContractParticipant = isEligibleContractParticipant;
    return this;
  }

  /**
   * List of eligible contract participant types.
   * @return eligibleContractParticipantTypes
   **/
  @JsonProperty(JSON_PROPERTY_ELIGIBLE_CONTRACT_PARTICIPANT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public List<@Valid DfaEligibleContractParticipantType> getEligibleContractParticipantTypes() {
    return eligibleContractParticipantTypes;
  }

  /**
   * Set eligibleContractParticipantTypes
   */
  @JsonProperty(JSON_PROPERTY_ELIGIBLE_CONTRACT_PARTICIPANT_TYPES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setEligibleContractParticipantTypes(List<@Valid DfaEligibleContractParticipantType> eligibleContractParticipantTypes) {
    this.eligibleContractParticipantTypes = eligibleContractParticipantTypes;
  }

  public Dfa eligibleContractParticipantTypes(List<@Valid DfaEligibleContractParticipantType> eligibleContractParticipantTypes) {
    this.eligibleContractParticipantTypes = eligibleContractParticipantTypes;
    return this;
  }

  public Dfa addEligibleContractParticipantTypesItem(DfaEligibleContractParticipantType eligibleContractParticipantTypesItem) {
    if (this.eligibleContractParticipantTypes == null) {
      this.eligibleContractParticipantTypes = new ArrayList<>();
    }
    this.eligibleContractParticipantTypes.add(eligibleContractParticipantTypesItem);
    return this;
  }

  /**
   * Whether the operation has a clearing exception, which is decided together with the election for DFA question &#39;Standing End-User Exception&#39;
   * @return hasStandingOptOutAnnualFiling
   **/
  @JsonProperty(JSON_PROPERTY_HAS_STANDING_OPT_OUT_ANNUAL_FILING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHasStandingOptOutAnnualFiling() {
    return hasStandingOptOutAnnualFiling;
  }

  /**
   * Set hasStandingOptOutAnnualFiling
   */
  @JsonProperty(JSON_PROPERTY_HAS_STANDING_OPT_OUT_ANNUAL_FILING)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasStandingOptOutAnnualFiling(Boolean hasStandingOptOutAnnualFiling) {
    this.hasStandingOptOutAnnualFiling = hasStandingOptOutAnnualFiling;
  }

  public Dfa hasStandingOptOutAnnualFiling(Boolean hasStandingOptOutAnnualFiling) {
    this.hasStandingOptOutAnnualFiling = hasStandingOptOutAnnualFiling;
    return this;
  }

  /**
   * Whether the counterparty has answered &#39;Yes&#39; to the Questionnaire for Covered Forex Transactions
   * @return isCoveredForexTransactions
   **/
  @JsonProperty(JSON_PROPERTY_IS_COVERED_FOREX_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsCoveredForexTransactions() {
    return isCoveredForexTransactions;
  }

  /**
   * Set isCoveredForexTransactions
   */
  @JsonProperty(JSON_PROPERTY_IS_COVERED_FOREX_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsCoveredForexTransactions(Boolean isCoveredForexTransactions) {
    this.isCoveredForexTransactions = isCoveredForexTransactions;
  }

  public Dfa isCoveredForexTransactions(Boolean isCoveredForexTransactions) {
    this.isCoveredForexTransactions = isCoveredForexTransactions;
    return this;
  }

  /**
   * Whether the counterparty has answered &#39;Yes&#39; to the Questionnaire for Covered Derivative Transactions
   * @return isCoveredDerivativeTransactions
   **/
  @JsonProperty(JSON_PROPERTY_IS_COVERED_DERIVATIVE_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsCoveredDerivativeTransactions() {
    return isCoveredDerivativeTransactions;
  }

  /**
   * Set isCoveredDerivativeTransactions
   */
  @JsonProperty(JSON_PROPERTY_IS_COVERED_DERIVATIVE_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsCoveredDerivativeTransactions(Boolean isCoveredDerivativeTransactions) {
    this.isCoveredDerivativeTransactions = isCoveredDerivativeTransactions;
  }

  public Dfa isCoveredDerivativeTransactions(Boolean isCoveredDerivativeTransactions) {
    this.isCoveredDerivativeTransactions = isCoveredDerivativeTransactions;
    return this;
  }

  /**
   * Whether the counterparty has answered &#39;Yes&#39; to the Questionnaire for Additional Pre-Trade Mid-Market Marks (PTMM) Transactions
   * @return isAdditionalPtmmTransactions
   **/
  @JsonProperty(JSON_PROPERTY_IS_ADDITIONAL_PTMM_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getIsAdditionalPtmmTransactions() {
    return isAdditionalPtmmTransactions;
  }

  /**
   * Set isAdditionalPtmmTransactions
   */
  @JsonProperty(JSON_PROPERTY_IS_ADDITIONAL_PTMM_TRANSACTIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setIsAdditionalPtmmTransactions(Boolean isAdditionalPtmmTransactions) {
    this.isAdditionalPtmmTransactions = isAdditionalPtmmTransactions;
  }

  public Dfa isAdditionalPtmmTransactions(Boolean isAdditionalPtmmTransactions) {
    this.isAdditionalPtmmTransactions = isAdditionalPtmmTransactions;
    return this;
  }

  /**
   * Whether the Pre-Trade Mid-Market Marks (PTMM) can be provided to the counterparty orally prior to the execution. Even if the answer is &#39;Yes&#39;, the PTMM must also be provided in written format by the end of the day of execution.
   * @return hasOralDisclosurePtmmElection
   **/
  @JsonProperty(JSON_PROPERTY_HAS_ORAL_DISCLOSURE_PTMM_ELECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public Boolean getHasOralDisclosurePtmmElection() {
    return hasOralDisclosurePtmmElection;
  }

  /**
   * Set hasOralDisclosurePtmmElection
   */
  @JsonProperty(JSON_PROPERTY_HAS_ORAL_DISCLOSURE_PTMM_ELECTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setHasOralDisclosurePtmmElection(Boolean hasOralDisclosurePtmmElection) {
    this.hasOralDisclosurePtmmElection = hasOralDisclosurePtmmElection;
  }

  public Dfa hasOralDisclosurePtmmElection(Boolean hasOralDisclosurePtmmElection) {
    this.hasOralDisclosurePtmmElection = hasOralDisclosurePtmmElection;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dfa {\n");
    
    sb.append("    ownershipType: ").append(toIndentedString(ownershipType)).append("\n");
    sb.append("    isEligibleContractParticipant: ").append(toIndentedString(isEligibleContractParticipant)).append("\n");
    sb.append("    eligibleContractParticipantTypes: ").append(toIndentedString(eligibleContractParticipantTypes)).append("\n");
    sb.append("    hasStandingOptOutAnnualFiling: ").append(toIndentedString(hasStandingOptOutAnnualFiling)).append("\n");
    sb.append("    isCoveredForexTransactions: ").append(toIndentedString(isCoveredForexTransactions)).append("\n");
    sb.append("    isCoveredDerivativeTransactions: ").append(toIndentedString(isCoveredDerivativeTransactions)).append("\n");
    sb.append("    isAdditionalPtmmTransactions: ").append(toIndentedString(isAdditionalPtmmTransactions)).append("\n");
    sb.append("    hasOralDisclosurePtmmElection: ").append(toIndentedString(hasOralDisclosurePtmmElection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

