/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  DfaEligibleContractParticipantType.JSON_PROPERTY_CODE,
  DfaEligibleContractParticipantType.JSON_PROPERTY_DESCRIPTION
})
/**
  * Data structure containing DFA Eligible Contract Participant Type for the entity.
  */

public class DfaEligibleContractParticipantType  implements Serializable {
  
  public enum CodeEnum {

    APREGBR(String.valueOf("APREGBR")), ALTCOM(String.valueOf("ALTCOM")), BRDEAT(String.valueOf("BRDEAT")), BRDENONAT(String.valueOf("BRDENONAT")), ELICOMMOD(String.valueOf("ELICOMMOD")), ELIGOV(String.valueOf("ELIGOV")), ELIINDIV(String.valueOf("ELIINDIV")), ELIINSUR(String.valueOf("ELIINSUR")), ELIINVEST(String.valueOf("ELIINVEST")), EMPBENPLAN(String.valueOf("EMPBENPLAN")), FCMNATPER(String.valueOf("FCMNATPER")), FCMNONNAT(String.valueOf("FCMNONNAT")), FINANENT(String.valueOf("FINANENT")), FINANINST(String.valueOf("FINANINST")), FLOORBRTR(String.valueOf("FLOORBRTR")), HEDGEECP(String.valueOf("HEDGEECP")), HEDGIECP(String.valueOf("HEDGIECP")), INVBANKHO(String.valueOf("INVBANKHO")), LARGEENT(String.valueOf("LARGEENT")), MAJORSBP(String.valueOf("MAJORSBP")), MAJORSWAP(String.valueOf("MAJORSWAP")), OTHPERSON(String.valueOf("OTHPERSON")), SBSWAP(String.valueOf("SBSWAP")), SPECIALENT(String.valueOf("SPECIALENT")), SWAPDEAL(String.valueOf("SWAPDEAL"));


    String value;

    CodeEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static CodeEnum fromValue(String value) {
            for (CodeEnum b : CodeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_CODE = "code";
 /**
  * DFA Eligible Contract Participant Type Code. Possible values are: - APREGBR: Authorised Person of Registered Broker - ALTCOM: Alternative Commodity Pool - BRDEAT: Broker or Dealer is a Natural Person - BRDENONAT: Broker or Dealer is a Non-Natural Person - ELICOMMOD: Eligible Commodity Pool - ELIGOV: Eligible Government Entity - ELIINDIV: Eligible Individual - ELIINSUR: Eligible Insurance Company - ELIINVEST: Eligible Investment Company - EMPBENPLAN: Employee Benefits Plan - FCMNATPER: FCM (Futures Commission Merchant) is a Natural Person - FCMNONNAT: FCM (Futures Commission Merchant) is a Non-Natural Person - FINANENT: Financial Entity - FINANINST: Financial institution - FLOORBRTR: Floor Broker or Floor Trader - HEDGEECP: Hedging Entity ECP (Eligible Contract Participant) - HEDGIECP: Hedging Individual ECP (Eligible Contract Participant) - INVBANKHO: Investment Bank Holding Company - LARGEENT: Large Entity - MAJORSBP: Major Security-Based Swap Participant - MAJORSWAP: Major Swap Participant - OTHPERSON: Other Eligible Person - SBSWAP: Security-Based Swap Dealer - SPECIALENT: Special Entity - SWAPDEAL: Swap Dealer 
  */
  
  private CodeEnum code;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
 /**
  * Eligible Contract Participant Type Description
  */
  
  private String description;

  public DfaEligibleContractParticipantType() {
  }

 @JsonCreator
  public DfaEligibleContractParticipantType(
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION) String description
  ) {
    this.description = description;
  }
  
  /**
   * DFA Eligible Contract Participant Type Code. Possible values are: - APREGBR: Authorised Person of Registered Broker - ALTCOM: Alternative Commodity Pool - BRDEAT: Broker or Dealer is a Natural Person - BRDENONAT: Broker or Dealer is a Non-Natural Person - ELICOMMOD: Eligible Commodity Pool - ELIGOV: Eligible Government Entity - ELIINDIV: Eligible Individual - ELIINSUR: Eligible Insurance Company - ELIINVEST: Eligible Investment Company - EMPBENPLAN: Employee Benefits Plan - FCMNATPER: FCM (Futures Commission Merchant) is a Natural Person - FCMNONNAT: FCM (Futures Commission Merchant) is a Non-Natural Person - FINANENT: Financial Entity - FINANINST: Financial institution - FLOORBRTR: Floor Broker or Floor Trader - HEDGEECP: Hedging Entity ECP (Eligible Contract Participant) - HEDGIECP: Hedging Individual ECP (Eligible Contract Participant) - INVBANKHO: Investment Bank Holding Company - LARGEENT: Large Entity - MAJORSBP: Major Security-Based Swap Participant - MAJORSWAP: Major Swap Participant - OTHPERSON: Other Eligible Person - SBSWAP: Security-Based Swap Dealer - SPECIALENT: Special Entity - SWAPDEAL: Swap Dealer 
   * @return code
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CodeEnum getCode() {
    return code;
  }

  /**
   * Set code
   */
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(CodeEnum code) {
    this.code = code;
  }

  public DfaEligibleContractParticipantType code(CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Eligible Contract Participant Type Description
   * @return description
   **/
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }



  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DfaEligibleContractParticipantType {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

