/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Document.JSON_PROPERTY_DOCUMENT_NUMBER,
  Document.JSON_PROPERTY_DOCUMENT_TYPE_CODE,
  Document.JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION
})
/**
  * Data structure containing information about an identification document for a person or an organization
  */

public class Document  implements Serializable {
  
  public static final String JSON_PROPERTY_DOCUMENT_NUMBER = "documentNumber";
 /**
  * Document number
  */
  
  private String documentNumber;

  public enum DocumentTypeCodeEnum {

    SSN(String.valueOf("SSN")), EIN(String.valueOf("EIN")), TAX_ID(String.valueOf("TAX_ID")), UNDEF(String.valueOf("UNDEF")), AEI(String.valueOf("AEI")), BSC(String.valueOf("BSC")), IBN(String.valueOf("IBN")), ISN(String.valueOf("ISN"));


    String value;

    DocumentTypeCodeEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static DocumentTypeCodeEnum fromValue(String value) {
            for (DocumentTypeCodeEnum b : DocumentTypeCodeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_DOCUMENT_TYPE_CODE = "documentTypeCode";
 /**
  * Document type code. Possible values are: - SSN: SOCIAL SECURITY NUMBER - EIN: EMPLOYER IDENTIFICATION NUMBER - TAX_ID: Tax ID - UNDEF: Undefined - AEI: Applied For EIN - BSC: BUSINESS CERTIFICATE/ARTICLES - IBN: IBAN - International Bank Account Number - ISN: ISIN - INTERNATIONAL SECURITIES IDENTIFICATION NUMBER 
  */
  
  private DocumentTypeCodeEnum documentTypeCode;

  public static final String JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION = "documentTypeDescription";
 /**
  * Document type description
  */
  
  private String documentTypeDescription;

  public Document() {
  }

 @JsonCreator
  public Document(
    @JsonProperty(value = JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION) String documentTypeDescription
  ) {
    this.documentTypeDescription = documentTypeDescription;
  }
  
  /**
   * Document number
   * @return documentNumber
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_DOCUMENT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getDocumentNumber() {
    return documentNumber;
  }

  /**
   * Set documentNumber
   */
  @JsonProperty(JSON_PROPERTY_DOCUMENT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocumentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
  }

  public Document documentNumber(String documentNumber) {
    this.documentNumber = documentNumber;
    return this;
  }

  /**
   * Document type code. Possible values are: - SSN: SOCIAL SECURITY NUMBER - EIN: EMPLOYER IDENTIFICATION NUMBER - TAX_ID: Tax ID - UNDEF: Undefined - AEI: Applied For EIN - BSC: BUSINESS CERTIFICATE/ARTICLES - IBN: IBAN - International Bank Account Number - ISN: ISIN - INTERNATIONAL SECURITIES IDENTIFICATION NUMBER 
   * @return documentTypeCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public DocumentTypeCodeEnum getDocumentTypeCode() {
    return documentTypeCode;
  }

  /**
   * Set documentTypeCode
   */
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDocumentTypeCode(DocumentTypeCodeEnum documentTypeCode) {
    this.documentTypeCode = documentTypeCode;
  }

  public Document documentTypeCode(DocumentTypeCodeEnum documentTypeCode) {
    this.documentTypeCode = documentTypeCode;
    return this;
  }

  /**
   * Document type description
   * @return documentTypeDescription
   **/
  @JsonProperty(JSON_PROPERTY_DOCUMENT_TYPE_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDocumentTypeDescription() {
    return documentTypeDescription;
  }



  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Document {\n");
    
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    documentTypeCode: ").append(toIndentedString(documentTypeCode)).append("\n");
    sb.append("    documentTypeDescription: ").append(toIndentedString(documentTypeDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

