/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Date;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Emir.JSON_PROPERTY_CLASSIFICATION_DATE,
  Emir.JSON_PROPERTY_CRD_CLEARING_OBLIGATION_CATEGORY
})
/**
  * Data structure containing European Market Infrastructure Regulation (EMIR)
  */

public class Emir  implements Serializable {
  
  public static final String JSON_PROPERTY_CLASSIFICATION_DATE = "classificationDate";
 /**
  * Date when the classification of EMIR Source Class was done.  The value uses the complete data format defined in ISO 8601:  'YYYY-MM-DD'  Where: - YYYY: 4-digit year - MM: 2-digit month (for example, 01 = January) - DD: 2-digit day of the month (01 through 31)
  */
  
  private Date classificationDate;

  public enum CrdClearingObligationCategoryEnum {

    _1(String.valueOf("CAT_1")), _2(String.valueOf("CAT_2")), _3(String.valueOf("CAT_3")), _4(String.valueOf("CAT_4"));


    String value;

    CrdClearingObligationCategoryEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static CrdClearingObligationCategoryEnum fromValue(String value) {
            for (CrdClearingObligationCategoryEnum b : CrdClearingObligationCategoryEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_CRD_CLEARING_OBLIGATION_CATEGORY = "crdClearingObligationCategory";
 /**
  * Clearing obligation category of the entity for Credit Derivatives (CRD) contracts. Possible values are: - CAT_1: Category 1 - CAT_2: Category 2 - CAT_3: Category 3 - CAT_4: Category 4 
  */
  
  private CrdClearingObligationCategoryEnum crdClearingObligationCategory;

  /**
   * Date when the classification of EMIR Source Class was done.  The value uses the complete data format defined in ISO 8601:  &#39;YYYY-MM-DD&#39;  Where: - YYYY: 4-digit year - MM: 2-digit month (for example, 01 &#x3D; January) - DD: 2-digit day of the month (01 through 31)
   * @return classificationDate
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CLASSIFICATION_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Date getClassificationDate() {
    return classificationDate;
  }

  /**
   * Set classificationDate
   */
  @JsonProperty(JSON_PROPERTY_CLASSIFICATION_DATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setClassificationDate(Date classificationDate) {
    this.classificationDate = classificationDate;
  }

  public Emir classificationDate(Date classificationDate) {
    this.classificationDate = classificationDate;
    return this;
  }

  /**
   * Clearing obligation category of the entity for Credit Derivatives (CRD) contracts. Possible values are: - CAT_1: Category 1 - CAT_2: Category 2 - CAT_3: Category 3 - CAT_4: Category 4 
   * @return crdClearingObligationCategory
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CRD_CLEARING_OBLIGATION_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CrdClearingObligationCategoryEnum getCrdClearingObligationCategory() {
    return crdClearingObligationCategory;
  }

  /**
   * Set crdClearingObligationCategory
   */
  @JsonProperty(JSON_PROPERTY_CRD_CLEARING_OBLIGATION_CATEGORY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCrdClearingObligationCategory(CrdClearingObligationCategoryEnum crdClearingObligationCategory) {
    this.crdClearingObligationCategory = crdClearingObligationCategory;
  }

  public Emir crdClearingObligationCategory(CrdClearingObligationCategoryEnum crdClearingObligationCategory) {
    this.crdClearingObligationCategory = crdClearingObligationCategory;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Emir {\n");
    
    sb.append("    classificationDate: ").append(toIndentedString(classificationDate)).append("\n");
    sb.append("    crdClearingObligationCategory: ").append(toIndentedString(crdClearingObligationCategory)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

