/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboentities.rest.dto.RiskSector;
import es.santander.scib.gboentities.rest.dto.RiskSegment;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  EntityRiskSegmentation.JSON_PROPERTY_RISK_SEGMENT,
  EntityRiskSegmentation.JSON_PROPERTY_RISK_SECTOR
})
@JsonTypeName("Entity_riskSegmentation")
/**
  * Data structure containing information about risk segmentation of the entity
  */

public class EntityRiskSegmentation  implements Serializable {
  
  public static final String JSON_PROPERTY_RISK_SEGMENT = "riskSegment";
  
  private RiskSegment riskSegment;

  public static final String JSON_PROPERTY_RISK_SECTOR = "riskSector";
  
  private RiskSector riskSector;

  /**
   * Get riskSegment
   * @return riskSegment
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_RISK_SEGMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RiskSegment getRiskSegment() {
    return riskSegment;
  }

  /**
   * Set riskSegment
   */
  @JsonProperty(JSON_PROPERTY_RISK_SEGMENT)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRiskSegment(RiskSegment riskSegment) {
    this.riskSegment = riskSegment;
  }

  public EntityRiskSegmentation riskSegment(RiskSegment riskSegment) {
    this.riskSegment = riskSegment;
    return this;
  }

  /**
   * Get riskSector
   * @return riskSector
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_RISK_SECTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public RiskSector getRiskSector() {
    return riskSector;
  }

  /**
   * Set riskSector
   */
  @JsonProperty(JSON_PROPERTY_RISK_SECTOR)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRiskSector(RiskSector riskSector) {
    this.riskSector = riskSector;
  }

  public EntityRiskSegmentation riskSector(RiskSector riskSector) {
    this.riskSector = riskSector;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityRiskSegmentation {\n");
    
    sb.append("    riskSegment: ").append(toIndentedString(riskSegment)).append("\n");
    sb.append("    riskSector: ").append(toIndentedString(riskSector)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

