/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboentities.rest.dto.StatusInfo;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  EntityRole.JSON_PROPERTY_ID,
  EntityRole.JSON_PROPERTY_CODE,
  EntityRole.JSON_PROPERTY_DESCRIPTION,
  EntityRole.JSON_PROPERTY_STATUS,
  EntityRole.JSON_PROPERTY_BOOKING_UNIT
})
/**
  * Data structure containing role information that an Entity is (or was) allowed to perform with a particular Booking Unit, as well as the current status of each.
  */

public class EntityRole  implements Serializable {
  
  public static final String JSON_PROPERTY_ID = "id";
 /**
  * Role identifier
  */
  
  private BigDecimal id;

  public enum CodeEnum {

    BRK(String.valueOf("BRK")), CDISS(String.valueOf("CDISS")), CLE(String.valueOf("CLE")), CLI(String.valueOf("CLI")), CUS(String.valueOf("CUS")), GUA(String.valueOf("GUA")), ISS(String.valueOf("ISS")), STK(String.valueOf("STK"));


    String value;

    CodeEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static CodeEnum fromValue(String value) {
            for (CodeEnum b : CodeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_CODE = "code";
 /**
  * Entity role code. Possible values are: - BRK: Broker - CDISS: Certificate of Deposit Issuer - CLE: Clearing - CLI: Client - CUS: Custody - GUA: Guarantor - ISS: Issuer - STK: Market 
  */
  
  private CodeEnum code;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
 /**
  * Role description
  */
  
  private String description;

  public static final String JSON_PROPERTY_STATUS = "status";
  
  private StatusInfo status;

  public static final String JSON_PROPERTY_BOOKING_UNIT = "bookingUnit";
 /**
  * Santander Bank Entity (Booking Unit) where the Entity is registered. This is used to route the creation.
  */
  
  private String bookingUnit;

  public EntityRole() {
  }

 @JsonCreator
  public EntityRole(
    @JsonProperty(value = JSON_PROPERTY_ID) BigDecimal id, 
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION) String description
  ) {
    this.id = id;
    this.description = description;
  }
  
  /**
   * Role identifier
   * @return id
   **/
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getId() {
    return id;
  }


  /**
   * Entity role code. Possible values are: - BRK: Broker - CDISS: Certificate of Deposit Issuer - CLE: Clearing - CLI: Client - CUS: Custody - GUA: Guarantor - ISS: Issuer - STK: Market 
   * @return code
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CodeEnum getCode() {
    return code;
  }

  /**
   * Set code
   */
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(CodeEnum code) {
    this.code = code;
  }

  public EntityRole code(CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * Role description
   * @return description
   **/
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  /**
   * Get status
   * @return status
   **/
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public StatusInfo getStatus() {
    return status;
  }

  /**
   * Set status
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStatus(StatusInfo status) {
    this.status = status;
  }

  public EntityRole status(StatusInfo status) {
    this.status = status;
    return this;
  }

  /**
   * Santander Bank Entity (Booking Unit) where the Entity is registered. This is used to route the creation.
   * @return bookingUnit
   **/
  @JsonProperty(JSON_PROPERTY_BOOKING_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getBookingUnit() {
    return bookingUnit;
  }

  /**
   * Set bookingUnit
   */
  @JsonProperty(JSON_PROPERTY_BOOKING_UNIT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setBookingUnit(String bookingUnit) {
    this.bookingUnit = bookingUnit;
  }

  public EntityRole bookingUnit(String bookingUnit) {
    this.bookingUnit = bookingUnit;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class EntityRole {\n");
    
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    bookingUnit: ").append(toIndentedString(bookingUnit)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

