/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboentities.rest.dto.Branch;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  MifidCategory.JSON_PROPERTY_CODE,
  MifidCategory.JSON_PROPERTY_DESCRIPTION,
  MifidCategory.JSON_PROPERTY_BRANCH
})
@JsonTypeName("Mifid_category")
/**
  * Data structure containing category for MIFID regulation branch segregation
  */

public class MifidCategory  implements Serializable {
  
  public enum CodeEnum {

    CE(String.valueOf("CE")), ELGCP(String.valueOf("ELGCP")), MI(String.valueOf("MI")), PF(String.valueOf("PF")), PROF(String.valueOf("PROF")), PS(String.valueOf("PS")), RTL(String.valueOf("RTL"));


    String value;

    CodeEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static CodeEnum fromValue(String value) {
            for (CodeEnum b : CodeEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_CODE = "code";
 /**
  * MiFID category code. Possible values are: - CE: ELIGIBLE COUNTERPARTY (CONTRAPARTE ELEGIBLE) - ELGCP: ELIGIBLE COUNTERPARTY - MI: RETAIL (MINORISTA) - PF: PROFESIONAL PER SE - PROF: PROFESSIONAL - PS: ELECTIVE PROFESSIONAL (PROFESIONAL BAJO SOLICITUD) - RTL: RETAIL 
  */
  
  private CodeEnum code;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
 /**
  * MIFID Category description
  */
  
  private String description;

  public static final String JSON_PROPERTY_BRANCH = "branch";
  
  private Branch branch;

  public MifidCategory() {
  }

 @JsonCreator
  public MifidCategory(
    @JsonProperty(value = JSON_PROPERTY_DESCRIPTION) String description
  ) {
    this.description = description;
  }
  
  /**
   * MiFID category code. Possible values are: - CE: ELIGIBLE COUNTERPARTY (CONTRAPARTE ELEGIBLE) - ELGCP: ELIGIBLE COUNTERPARTY - MI: RETAIL (MINORISTA) - PF: PROFESIONAL PER SE - PROF: PROFESSIONAL - PS: ELECTIVE PROFESSIONAL (PROFESIONAL BAJO SOLICITUD) - RTL: RETAIL 
   * @return code
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public CodeEnum getCode() {
    return code;
  }

  /**
   * Set code
   */
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCode(CodeEnum code) {
    this.code = code;
  }

  public MifidCategory code(CodeEnum code) {
    this.code = code;
    return this;
  }

  /**
   * MIFID Category description
   * @return description
   **/
  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getDescription() {
    return description;
  }


  /**
   * Get branch
   * @return branch
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_BRANCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Branch getBranch() {
    return branch;
  }

  /**
   * Set branch
   */
  @JsonProperty(JSON_PROPERTY_BRANCH)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setBranch(Branch branch) {
    this.branch = branch;
  }

  public MifidCategory branch(Branch branch) {
    this.branch = branch;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class MifidCategory {\n");
    
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    branch: ").append(toIndentedString(branch)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

