/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.gboentities.rest.dto.City;
import es.santander.scib.gboentities.rest.dto.Country;
import es.santander.scib.gboentities.rest.dto.State;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  PostalAddress.JSON_PROPERTY_CITY,
  PostalAddress.JSON_PROPERTY_ZIP_CODE,
  PostalAddress.JSON_PROPERTY_COUNTRY,
  PostalAddress.JSON_PROPERTY_STATE,
  PostalAddress.JSON_PROPERTY_STREET_NAME
})
/**
  * Data structure containing information that locates and identifies a postal address
  */

public class PostalAddress  implements Serializable {
  
  public static final String JSON_PROPERTY_CITY = "city";
  
  private City city;

  public static final String JSON_PROPERTY_ZIP_CODE = "zipCode";
 /**
  * Address ZIP code
  */
  
  private String zipCode;

  public static final String JSON_PROPERTY_COUNTRY = "country";
  
  private Country country;

  public static final String JSON_PROPERTY_STATE = "state";
  
  private State state;

  public static final String JSON_PROPERTY_STREET_NAME = "streetName";
 /**
  * Name of a street or thoroughfare
  */
  
  private String streetName;

  /**
   * Get city
   * @return city
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public City getCity() {
    return city;
  }

  /**
   * Set city
   */
  @JsonProperty(JSON_PROPERTY_CITY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCity(City city) {
    this.city = city;
  }

  public PostalAddress city(City city) {
    this.city = city;
    return this;
  }

  /**
   * Address ZIP code
   * @return zipCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getZipCode() {
    return zipCode;
  }

  /**
   * Set zipCode
   */
  @JsonProperty(JSON_PROPERTY_ZIP_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setZipCode(String zipCode) {
    this.zipCode = zipCode;
  }

  public PostalAddress zipCode(String zipCode) {
    this.zipCode = zipCode;
    return this;
  }

  /**
   * Get country
   * @return country
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public Country getCountry() {
    return country;
  }

  /**
   * Set country
   */
  @JsonProperty(JSON_PROPERTY_COUNTRY)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCountry(Country country) {
    this.country = country;
  }

  public PostalAddress country(Country country) {
    this.country = country;
    return this;
  }

  /**
   * Get state
   * @return state
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public State getState() {
    return state;
  }

  /**
   * Set state
   */
  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setState(State state) {
    this.state = state;
  }

  public PostalAddress state(State state) {
    this.state = state;
    return this;
  }

  /**
   * Name of a street or thoroughfare
   * @return streetName
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_STREET_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStreetName() {
    return streetName;
  }

  /**
   * Set streetName
   */
  @JsonProperty(JSON_PROPERTY_STREET_NAME)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStreetName(String streetName) {
    this.streetName = streetName;
  }

  public PostalAddress streetName(String streetName) {
    this.streetName = streetName;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PostalAddress {\n");
    
    sb.append("    city: ").append(toIndentedString(city)).append("\n");
    sb.append("    zipCode: ").append(toIndentedString(zipCode)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    streetName: ").append(toIndentedString(streetName)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

