/**
 * GBO Entities
 * It allows the possibility of standardizing the way entities are created and generated for the different regions and global entities of GBO (Global Backoffice), allowing the creation of entities in a single way for the different users with a new way that allows this action to be carried out. 
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: dario.vega@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.gboentities.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.math.BigDecimal;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  StatusInfo.JSON_PROPERTY_STATUS_ID,
  StatusInfo.JSON_PROPERTY_STATUS_CODE,
  StatusInfo.JSON_PROPERTY_STATUS_DESCRIPTION
})
/**
  * Data structure containing information about an item's status
  */

public class StatusInfo  implements Serializable {
  
  public static final String JSON_PROPERTY_STATUS_ID = "statusId";
 /**
  * Status ID
  */
  
  private BigDecimal statusId;

  public static final String JSON_PROPERTY_STATUS_CODE = "statusCode";
 /**
  * Status code
  */
  
  private String statusCode;

  public static final String JSON_PROPERTY_STATUS_DESCRIPTION = "statusDescription";
 /**
  * Status description
  */
  
  private String statusDescription;

  public StatusInfo() {
  }

 @JsonCreator
  public StatusInfo(
    @JsonProperty(value = JSON_PROPERTY_STATUS_ID) BigDecimal statusId, 
    @JsonProperty(value = JSON_PROPERTY_STATUS_DESCRIPTION) String statusDescription
  ) {
    this.statusId = statusId;
    this.statusDescription = statusDescription;
  }
  
  /**
   * Status ID
   * @return statusId
   **/
  @JsonProperty(JSON_PROPERTY_STATUS_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public BigDecimal getStatusId() {
    return statusId;
  }


  /**
   * Status code
   * @return statusCode
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public String getStatusCode() {
    return statusCode;
  }

  /**
   * Set statusCode
   */
  @JsonProperty(JSON_PROPERTY_STATUS_CODE)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatusCode(String statusCode) {
    this.statusCode = statusCode;
  }

  public StatusInfo statusCode(String statusCode) {
    this.statusCode = statusCode;
    return this;
  }

  /**
   * Status description
   * @return statusDescription
   **/
  @JsonProperty(JSON_PROPERTY_STATUS_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public String getStatusDescription() {
    return statusDescription;
  }



  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class StatusInfo {\n");
    
    sb.append("    statusId: ").append(toIndentedString(statusId)).append("\n");
    sb.append("    statusCode: ").append(toIndentedString(statusCode)).append("\n");
    sb.append("    statusDescription: ").append(toIndentedString(statusDescription)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

