/**
 * Getafe Events
 * Provide a service to send an event to the events framework (GETAFE), compliant with the format expected in the observability platform. It is indicated for those who cannot send events directly to it, but can post information to a http endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sara.camunas@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.getafe.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.getafe.rest.dto.Error;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Errors.JSON_PROPERTY_ERRORS
})
/**
  * Data structure containing the details for errors.
  */

public class Errors  implements Serializable {
  
  public static final String JSON_PROPERTY_ERRORS = "errors";
 /**
  * List of errors.
  */
  
  private List<@Valid Error> errors = new ArrayList<>();

  /**
   * List of errors.
   * @return errors
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid Error> getErrors() {
    return errors;
  }

  /**
   * Set errors
   */
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrors(List<@Valid Error> errors) {
    this.errors = errors;
  }

  public Errors errors(List<@Valid Error> errors) {
    this.errors = errors;
    return this;
  }

  public Errors addErrorsItem(Error errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Errors {\n");
    
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

