/**
 * Getafe Events
 * Provide a service to send an event to the events framework (GETAFE), compliant with the format expected in the observability platform. It is indicated for those who cannot send events directly to it, but can post information to a http endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sara.camunas@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.getafe.rest.dto;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import es.santander.scib.getafe.rest.dto.HealthComponent;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

@JsonPropertyOrder({
  Health.JSON_PROPERTY_COMPONENTS,
  Health.JSON_PROPERTY_STATUS
})
/**
  * Data structure containing information about the health response.
  */

public class Health  implements Serializable {
  
  public static final String JSON_PROPERTY_COMPONENTS = "components";
 /**
  * Data structure containing components information.
  */
  
  private List<@Valid HealthComponent> components = new ArrayList<>();

  public enum StatusEnum {

    UP(String.valueOf("UP")), DOWN(String.valueOf("DOWN")), UNKNOWN(String.valueOf("UNKNOWN")), OUT_OF_SERVICE(String.valueOf("OUT_OF_SERVICE"));


    String value;

    StatusEnum (String v) {
        value = v;
    }

    @JsonValue
    public String value() {
        return value;
    }

    @Override
    public String toString() {
        return String.valueOf(value);
    }

    @JsonCreator
        public static StatusEnum fromValue(String value) {
            for (StatusEnum b : StatusEnum.values()) {
                if (b.value.equals(value)) {
                    return b;
                }
            }
            throw new IllegalArgumentException("Unexpected value '" + value + "'");
        }
  }

  public static final String JSON_PROPERTY_STATUS = "status";
 /**
  * Status of the component.\\ - UP: Status indicating that the component or subsystem is functioning as expected. - DOWN: Status indicating that the component or subsystem has suffered an unexpected failure. - OUT_OF_SERVICE: Status indicating that the component or subsystem has been taken out of service and should not be used. - UNKNOWN: Status indicating that the component or subsystem is in an unknown state. 
  */
  
  private StatusEnum status;

  /**
   * Data structure containing components information.
   * @return components
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public List<@Valid HealthComponent> getComponents() {
    return components;
  }

  /**
   * Set components
   */
  @JsonProperty(JSON_PROPERTY_COMPONENTS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setComponents(List<@Valid HealthComponent> components) {
    this.components = components;
  }

  public Health components(List<@Valid HealthComponent> components) {
    this.components = components;
    return this;
  }

  public Health addComponentsItem(HealthComponent componentsItem) {
    if (this.components == null) {
      this.components = new ArrayList<>();
    }
    this.components.add(componentsItem);
    return this;
  }

  /**
   * Status of the component.\\ - UP: Status indicating that the component or subsystem is functioning as expected. - DOWN: Status indicating that the component or subsystem has suffered an unexpected failure. - OUT_OF_SERVICE: Status indicating that the component or subsystem has been taken out of service and should not be used. - UNKNOWN: Status indicating that the component or subsystem is in an unknown state. 
   * @return status
   **/
  @NotNull
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public StatusEnum getStatus() {
    return status;
  }

  /**
   * Set status
   */
  @JsonProperty(JSON_PROPERTY_STATUS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(StatusEnum status) {
    this.status = status;
  }

  public Health status(StatusEnum status) {
    this.status = status;
    return this;
  }


  /**
   * Create a string representation of this pojo.
   */
  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Health {\n");
    
    sb.append("    components: ").append(toIndentedString(components)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private static String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}

