/**
 * Document Data Extractor
 * This API extracts metadata from unstructured documents using artificial intelligence (AI).  The process is asynchronous and requires that the document from which metadata is to be extracted is first uploaded separately to a repository, as the document itself is not provided in the API request.  The API can be used to: - Initiate a metadata extraction. - Verify the status of a file extraction. - Retrieve the metadata from a file extraction - Send feedback for extracted metadata.
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: apiglobalgovernance@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.extractor.rest.client;

import jakarta.ws.rs.core.Response;

public class ApiException extends Exception {

  private static final long serialVersionUID = 1L;
  private Response response;

  public ApiException() {
    super();
  }

  public ApiException(Response response) {
    super("Api response has status code " + response.getStatus());
    this.response = response;
  }

  public Response getResponse() {
    return this.response;
  }
}
