/**
 * Getafe Events
 * Provide a service to send an event to the events framework (GETAFE), compliant with the format expected in the observability platform. It is indicated for those who cannot send events directly to it, but can post information to a http endpoint.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sara.camunas@gruposantander.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package es.santander.scib.getafe.rest.client;

import es.santander.scib.getafe.rest.dto.Errors;
import es.santander.scib.getafe.rest.dto.Event;

import java.io.InputStream;
import java.io.OutputStream;
import java.util.List;
import java.util.Map;
import java.util.Set;
import jakarta.ws.rs.*;
import jakarta.ws.rs.core.Response;
import jakarta.ws.rs.core.MediaType;

import jakarta.validation.constraints.*;
import jakarta.validation.Valid;

import org.eclipse.microprofile.rest.client.annotation.RegisterProvider;
import org.eclipse.microprofile.rest.client.inject.RegisterRestClient;

/**
 * Getafe Events
 *
 * <p>Provide a service to send an event to the events framework (GETAFE), compliant with the format expected in the observability platform. It is indicated for those who cannot send events directly to it, but can post information to a http endpoint.
 *
 */

@RegisterRestClient(configKey="scib-api-gateway")
@RegisterProvider(ApiExceptionMapper.class)
@Path("/events")
public interface EventsApi  {

    /**
     * Create an event to be sent to the events framework.
     *
     * Create the input event to send to a events framework topic.
     *
     */
    @POST
    
    @Consumes({ "application/json" })
    @Produces({ "application/json" })
    void createEvents(@HeaderParam("X-Topic")  @NotNull String xTopic, @HeaderParam("X-Santander-Client-Id")  @NotNull String xSantanderClientId, @Valid Event event, @HeaderParam("X-Key")  String xKey, @HeaderParam("X-Santander-Device")  String xSantanderDevice, @HeaderParam("X-B3-TraceId")  String xB3TraceId, @HeaderParam("X-B3-ParentSpanId")  String xB3ParentSpanId, @HeaderParam("X-B3-SpanId")  String xB3SpanId, @HeaderParam("X-B3-Sampled")  String xB3Sampled, @HeaderParam("Accept-Language")  String acceptLanguage, @HeaderParam("If-None-Match")  String ifNoneMatch, @HeaderParam("If-Match")  String ifMatch) throws ApiException, ProcessingException;
}
